# Generated by Django 6.0.7 on 2026-08-25 23:03
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("allies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="allies.ally",
                    ),
                ),
            ],
            options={
                "ordering": ("ally_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("send", "Send"), ("onboarding", "Onboarding")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(max_length=16000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "send_key_digest",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "content_fingerprint",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("ally",),
                name="chat_conversation_default_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "status"], name="chat_message_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="chat_message_sequence_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="chat_message_sequence_positive_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("origin", "send"), ("send_key_digest__gt", ""), ("sender", "user")
                ),
                fields=("conversation", "send_key_digest"),
                name="chat_message_send_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("origin", "send"), ("sender", "user"), ("status", "in_progress")
                ),
                fields=("conversation",),
                name="chat_message_active_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("content_fingerprint__regex", "^[0-9a-fA-F]{64}$"),
                        ("origin", "send"),
                        ("send_key_digest__regex", "^[0-9a-fA-F]{64}$"),
                        ("sender", "user"),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "send"),
                        ("send_key_digest", ""),
                        ("sender", "assistant"),
                        (
                            "status__in",
                            ("in_progress", "completed", "failed", "stopped"),
                        ),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "onboarding"),
                        ("send_key_digest", ""),
                        ("sender", "assistant"),
                        ("sequence", 1),
                        ("status", "completed"),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "onboarding"),
                        ("send_key_digest", ""),
                        ("sender", "user"),
                        ("sequence", 2),
                        ("status", "completed"),
                    ),
                    _connector="OR",
                ),
                name="chat_message_origin_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin__in", ("send", "onboarding")),
                    ("sender__in", ("user", "assistant")),
                ),
                name="chat_message_role_origin_chk",
            ),
        ),
    ]
