# Generated by Django 6.0.7 on 2026-08-26 01:05
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command_bytes", models.BinaryField(default=bytes)),
                (
                    "command_byte_length",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "command_sha256",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "command_fingerprint",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=90
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("accepted", "Accepted"),
                            ("reconciliation_needed", "Reconciliation needed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "receipt_digest",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="message",
            name="chat_message_origin_coherent",
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("awaiting_action", "Awaiting action"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("stopped", "Stopped"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("content_fingerprint__regex", "^[0-9a-fA-F]{64}$"),
                        ("origin", "send"),
                        ("send_key_digest__regex", "^[0-9a-fA-F]{64}$"),
                        ("sender", "user"),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "send"),
                        ("send_key_digest", ""),
                        ("sender", "assistant"),
                        (
                            "status__in",
                            (
                                "in_progress",
                                "awaiting_action",
                                "completed",
                                "failed",
                                "stopped",
                            ),
                        ),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "onboarding"),
                        ("send_key_digest", ""),
                        ("sender", "assistant"),
                        ("sequence", 1),
                        ("status", "completed"),
                    ),
                    models.Q(
                        ("content_fingerprint", ""),
                        ("origin", "onboarding"),
                        ("send_key_digest", ""),
                        ("sender", "user"),
                        ("sequence", 2),
                        ("status", "completed"),
                    ),
                    _connector="OR",
                ),
                name="chat_message_origin_coherent",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoutbox",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_outbox",
                to="chat.message",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at", "lease_expires_at"],
                name="chat_dispatch_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("command_byte_length__gte", 0)),
                name="chat_dispatch_command_length_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("command_sha256", ""),
                    ("command_sha256__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="chat_dispatch_command_sha_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="chat_dispatch_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_count__gte", 0), ("attempt_count__lte", 5)
                ),
                name="chat_dispatch_attempt_count_bounded",
            ),
        ),
    ]
