# Generated by Django 6.0.7 on 2026-09-10 07:46
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_message_queue_claims"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
