# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chat", "0008_dispatch_file_manifest")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="foundry_binding_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        )
    ]
