# Generated by Django 6.0.7 on 2026-10-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_merge_20260910_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="steered_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
