"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import math
import os
import re
from pathlib import Path
from urllib.parse import unquote, urlparse

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from django.utils.log import DEFAULT_LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [
        item.strip()
        for item in os.environ.get(name, default).split(",")
        if item.strip()
    ]


def env_positive_float(name: str, default: float) -> float:
    raw = os.environ.get(name, str(default))
    try:
        value = float(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be a positive number") from exc
    if value <= 0:
        raise ImproperlyConfigured(f"{name} must be a positive number")
    return value


def env_positive_int(name: str, default: int) -> int:
    raw = os.environ.get(name, str(default))
    try:
        value = int(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be a positive integer") from exc
    if value <= 0:
        raise ImproperlyConfigured(f"{name} must be a positive integer")
    return value


def env_bounded_int(name: str, default: int, minimum: int, maximum: int) -> int:
    value = env_positive_int(name, default)
    if not minimum <= value <= maximum:
        raise ImproperlyConfigured(f"{name} must be between {minimum} and {maximum}")
    return value


def env_sample_rate(name: str, default: float) -> float:
    raw = os.environ.get(name, str(default))
    try:
        value = float(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be between 0 and 1") from exc
    if not 0 <= value <= 1:
        raise ImproperlyConfigured(f"{name} must be between 0 and 1")
    return value


ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS = env_positive_float(
    "ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS", 2.0
)
ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS = env_positive_float(
    "ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS", 5.0
)
if ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS >= ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS:
    raise ImproperlyConfigured(
        "ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS must be less than "
        "ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS"
    )
DATABASE_CONNECT_TIMEOUT_SECONDS = env_positive_int(
    "DATABASE_CONNECT_TIMEOUT_SECONDS", 10
)
CACHE_CONNECT_TIMEOUT_SECONDS = env_positive_float(
    "CACHE_CONNECT_TIMEOUT_SECONDS", 10.0
)
CACHE_SOCKET_TIMEOUT_SECONDS = env_positive_float("CACHE_SOCKET_TIMEOUT_SECONDS", 10.0)
HEALTH_CACHE_OPERATION_TIMEOUT_SECONDS = max(
    0.001,
    min(
        ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS,
        (ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS - ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS)
        / 4,
    ),
)


def database_from_url(
    value: str,
    *,
    connect_timeout: int | None = None,
    conn_max_age: int | None = None,
) -> dict[str, object]:
    parsed = urlparse(value)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured("DATABASE_URL must use postgres:// or postgresql://")
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": parsed.port or 5432,
        "CONN_MAX_AGE": (
            int(os.environ.get("DATABASE_CONN_MAX_AGE", "60"))
            if conn_max_age is None
            else conn_max_age
        ),
        "OPTIONS": {
            "connect_timeout": (
                DATABASE_CONNECT_TIMEOUT_SECONDS
                if connect_timeout is None
                else connect_timeout
            ),
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DJANGO_DEBUG", True)

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DEBUG is false")
    SECRET_KEY = "django-insecure-allies-cloud-local-development-only"

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1],testserver" if DEBUG else ""
)


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "ninja_extra",
    "auths",
    "workspaces",
    "waitlist",
    "allies",
    "routines",
    "chat",
    "files",
    "activities",
    "integrations",
    "model_keys",
    "devtools",
]

ALLIES_RAILWAY_PROXY_MODE = env_bool("ALLIES_RAILWAY_PROXY_MODE", False)

# OBS-001 is stdout-first; routine successes default to 5% to bound normal
# volume, while errors, retries, and slow events remain retained by contract.
# The optional sink is deliberately disabled until a collector adapter has its
# own bounded timeout and retry contract.
ALLIES_WIDE_EVENTS_ENABLED = env_bool("ALLIES_WIDE_EVENTS_ENABLED", True)
ALLIES_WIDE_EVENTS_SUCCESS_SAMPLE_RATE = env_sample_rate(
    "ALLIES_WIDE_EVENTS_SUCCESS_SAMPLE_RATE", 0.05
)
ALLIES_WIDE_EVENTS_SLOW_MS = env_positive_int("ALLIES_WIDE_EVENTS_SLOW_MS", 1000)
ALLIES_WIDE_EVENTS_MAX_BYTES = env_positive_int(
    "ALLIES_WIDE_EVENTS_MAX_BYTES", 16 * 1024
)
ALLIES_WIDE_EVENTS_SINK_ENABLED = env_bool("ALLIES_WIDE_EVENTS_SINK_ENABLED", False)
ALLIES_WIDE_EVENTS_MAX_QUEUE_SIZE = env_positive_int(
    "ALLIES_WIDE_EVENTS_MAX_QUEUE_SIZE", 256
)

_COMMON_MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
MIDDLEWARE = [
    "config.middleware.TrustedProxyHeadersMiddleware",
    "observability.middleware.WideEventMiddleware",
    "django.middleware.security.SecurityMiddleware",
    *_COMMON_MIDDLEWARE,
]
if not DEBUG:
    MIDDLEWARE.insert(3, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL", "")
DATABASES = {
    "default": database_from_url(DATABASE_URL)
    if DATABASE_URL
    else {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
if DATABASE_URL:
    health_connect_timeout = max(
        1,
        math.floor(
            min(
                ALLIES_HEALTH_OPERATION_TIMEOUT_SECONDS,
                ALLIES_HEALTH_TOTAL_TIMEOUT_SECONDS,
            )
        ),
    )
    DATABASES["health"] = database_from_url(
        DATABASE_URL,
        connect_timeout=health_connect_timeout,
        conn_max_age=0,
    )
    DATABASES["health"]["TEST"] = {"MIRROR": "default"}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

LOGGING = {
    **DEFAULT_LOGGING,
    "formatters": {
        **DEFAULT_LOGGING["formatters"],
        "allies": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        **DEFAULT_LOGGING["handlers"],
        "allies_console": {
            "class": "logging.StreamHandler",
            "formatter": "allies",
        },
    },
    "loggers": {
        **DEFAULT_LOGGING["loggers"],
        "allies.auth": {
            "handlers": ["allies_console"],
            "level": "INFO",
            "propagate": False,
        },
        "allies.waitlist": {
            "handlers": ["allies_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# AUTH-001 security and provider configuration. Local development is explicit;
# production values are supplied by the deployment secret/configuration store.
AUTH_USER_MODEL = "auths.User"

CSRF_TRUSTED_ORIGINS = env_list(
    "ALLIES_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000" if DEBUG else "",
)
CORS_ALLOWED_ORIGINS = [origin for origin in CSRF_TRUSTED_ORIGINS if "*" not in origin]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^" + re.escape(origin).replace(r"\*", r"[^./:]+") + r"$"
    for origin in CSRF_TRUSTED_ORIGINS
    if "*" in origin
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [*default_headers, "idempotency-key", "last-event-id"]
CORS_EXPOSE_HEADERS = ["X-CSRFToken", "X-Request-ID"]

LOGGING = {
    **DEFAULT_LOGGING,
    "formatters": {
        **DEFAULT_LOGGING["formatters"],
        "allies": {
            "()": "observability.events.AuditEventFormatter",
        },
        "wide_event": {"()": "observability.events.WideEventFormatter"},
    },
    "handlers": {
        **DEFAULT_LOGGING["handlers"],
        "allies_console": {
            "class": "logging.StreamHandler",
            "formatter": "allies",
        },
        "wide_event_stdout": {
            "class": "logging.StreamHandler",
            "formatter": "wide_event",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        **DEFAULT_LOGGING["loggers"],
        "allies.auth": {
            "handlers": ["allies_console"],
            "level": "INFO",
            "propagate": False,
        },
        "allies.waitlist": {
            "handlers": ["allies_console"],
            "level": "INFO",
            "propagate": False,
        },
        "allies.observability": {
            "handlers": ["wide_event_stdout"],
            "level": "INFO",
            "propagate": False,
        },
        "allies.chat": {
            "handlers": ["allies_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_PATH = "/"

ALLIES_TRUST_FORWARDED_PROTO = env_bool("ALLIES_TRUST_FORWARDED_PROTO", False)
if ALLIES_RAILWAY_PROXY_MODE:
    # Railway mode is an explicit deployment contract: the managed edge is
    # the only supported ingress and its HTTPS signal must not be disabled by
    # an inherited local `.env` value.
    ALLIES_TRUST_FORWARDED_PROTO = True
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if ALLIES_TRUST_FORWARDED_PROTO else None
)
USE_X_FORWARDED_HOST = env_bool("ALLIES_TRUST_FORWARDED_HOST", False)
ALLIES_TRUST_FORWARDED_FOR = env_bool("ALLIES_TRUST_FORWARDED_FOR", False)
ALLIES_TRUSTED_PROXY_IPS = env_list("ALLIES_TRUSTED_PROXY_IPS")
SECURE_SSL_REDIRECT = not DEBUG
# Railway performs its private readiness probe over HTTP. Outside Railway
# mode, health checks use the same HTTPS policy as every other route.
SECURE_REDIRECT_EXEMPT = [r"^/?api/v1/health$"] if ALLIES_RAILWAY_PROXY_MODE else []
SECURE_HSTS_SECONDS = (
    0 if DEBUG else int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True

ALLIES_AUTH_ACCESS_COOKIE = "allies_access"
ALLIES_AUTH_REFRESH_COOKIE = "allies_refresh"
ALLIES_AUTH_FLOW_COOKIE = "allies_auth_flow"
ALLIES_AUTH_THROTTLE_COOKIE = "allies_throttle"
ALLIES_AUTH_ACCESS_COOKIE_PATH = "/api/"
ALLIES_AUTH_REFRESH_COOKIE_PATH = "/api/v1/auths/"
ALLIES_AUTH_FLOW_COOKIE_PATH = "/api/v1/auths/callback/"
ALLIES_AUTH_THROTTLE_COOKIE_PATH = "/api/"
ALLIES_AUTH_COOKIE_SECURE = not DEBUG
ALLIES_AUTH_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
ALLIES_AUTH_ACCESS_TTL_SECONDS = int(
    os.environ.get("ALLIES_AUTH_ACCESS_TTL_SECONDS", "600")
)
ALLIES_AUTH_FLOW_TTL_SECONDS = int(
    os.environ.get("ALLIES_AUTH_FLOW_TTL_SECONDS", "600")
)
ALLIES_AUTH_REFRESH_IDLE_SECONDS = int(
    os.environ.get("ALLIES_AUTH_REFRESH_IDLE_SECONDS", str(14 * 24 * 60 * 60))
)
ALLIES_AUTH_REFRESH_ABSOLUTE_SECONDS = int(
    os.environ.get("ALLIES_AUTH_REFRESH_ABSOLUTE_SECONDS", str(30 * 24 * 60 * 60))
)
ALLIES_AUTH_JWT_KEY = os.environ.get("ALLIES_AUTH_JWT_KEY", "")
ALLIES_AUTH_JWT_ISSUER = os.environ.get("ALLIES_AUTH_JWT_ISSUER", "allies-cloud")
ALLIES_AUTH_JWT_AUDIENCE = os.environ.get(
    "ALLIES_AUTH_JWT_AUDIENCE", "allies-interface"
)
ALLIES_AUTH_DIGEST_KEY = os.environ.get("ALLIES_AUTH_DIGEST_KEY", "")

ALLIES_CHAT_MAX_PENDING_MESSAGES = env_bounded_int(
    "ALLIES_CHAT_MAX_PENDING_MESSAGES", 20, 1, 100
)
ALLIES_CHAT_QUEUE_ADMISSION_ENABLED = env_bool(
    "ALLIES_CHAT_QUEUE_ADMISSION_ENABLED", True
)
ALLIES_CHAT_SEND_RATE_LIMIT = env_bounded_int("ALLIES_CHAT_SEND_RATE_LIMIT", 30, 1, 120)
ALLIES_CHAT_SEND_RATE_PERIOD_SECONDS = env_bounded_int(
    "ALLIES_CHAT_SEND_RATE_PERIOD_SECONDS", 600, 60, 3600
)
ALLIES_CHAT_CURSOR_ACTIVE_KEY_ID = os.environ.get(
    "ALLIES_CHAT_CURSOR_ACTIVE_KEY_ID", "v1"
)
ALLIES_CHAT_CURSOR_KEY = os.environ.get(
    "ALLIES_CHAT_CURSOR_KEY",
    ALLIES_AUTH_DIGEST_KEY or "allies-local-chat-cursor-key-not-for-production",
)
ALLIES_CHAT_CURSOR_KEYS = os.environ.get("ALLIES_CHAT_CURSOR_KEYS", "{}")
ALLIES_CHAT_CURSOR_PREVIOUS_KEYS = os.environ.get(
    "ALLIES_CHAT_CURSOR_PREVIOUS_KEYS", "{}"
)
ALLIES_CHAT_CURSOR_TTL_SECONDS = env_bounded_int(
    "ALLIES_CHAT_CURSOR_TTL_SECONDS", 3600, 1, 86_400
)

ALLIES_AUTH_FAKE_PROVIDER_ENABLED = env_bool("ALLIES_AUTH_FAKE_PROVIDER_ENABLED", False)
ALLIES_BETA_INVITES_REQUIRED = env_bool("ALLIES_BETA_INVITES_REQUIRED", True)
ALLIES_AUTH_INVITE_CLAIM_LIMIT = env_bounded_int(
    "ALLIES_AUTH_INVITE_CLAIM_LIMIT", 10, 1, 600
)
ALLIES_AUTH_INVITE_CLAIM_GLOBAL_LIMIT = env_bounded_int(
    "ALLIES_AUTH_INVITE_CLAIM_GLOBAL_LIMIT", 600, 1, 600
)
ALLIES_AUTH_INVITE_CLAIM_RATE_LIMIT_PERIOD_SECONDS = env_bounded_int(
    "ALLIES_AUTH_INVITE_CLAIM_RATE_LIMIT_PERIOD_SECONDS", 60, 1, 3600
)
ALLIES_AUTH_GOOGLE_CLIENT_ID = os.environ.get("ALLIES_AUTH_GOOGLE_CLIENT_ID", "")
ALLIES_AUTH_GOOGLE_CLIENT_SECRET = os.environ.get(
    "ALLIES_AUTH_GOOGLE_CLIENT_SECRET", ""
)
ALLIES_AUTH_GOOGLE_REDIRECT_URI = os.environ.get("ALLIES_AUTH_GOOGLE_REDIRECT_URI", "")
ALLIES_AUTH_GOOGLE_ENABLED = env_bool("ALLIES_AUTH_GOOGLE_ENABLED", False)
ALLIES_AUTH_GOOGLE_NATIVE_REDIRECT_URI = os.environ.get(
    "ALLIES_AUTH_GOOGLE_NATIVE_REDIRECT_URI", ""
)
ALLIES_AUTH_NATIVE_ENABLED = env_bool("ALLIES_AUTH_NATIVE_ENABLED", False)
ALLIES_AUTH_NATIVE_REDIRECT_URIS = env_list("ALLIES_AUTH_NATIVE_REDIRECT_URIS")
ALLIES_AUTH_NATIVE_TRANSACTION_TTL_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_TRANSACTION_TTL_SECONDS", "600")
)
ALLIES_AUTH_NATIVE_EXCHANGE_TTL_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_EXCHANGE_TTL_SECONDS", "60")
)
ALLIES_AUTH_NATIVE_PROVIDER_TIMEOUT_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_PROVIDER_TIMEOUT_SECONDS", "15")
)
ALLIES_AUTH_NATIVE_CLAIM_LEASE_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_CLAIM_LEASE_SECONDS", "30")
)
ALLIES_AUTH_NATIVE_TERMINAL_RETENTION_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_TERMINAL_RETENTION_SECONDS", "86400")
)
ALLIES_AUTH_NATIVE_SIGN_IN_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_SIGN_IN_LIMIT", "10")
)
ALLIES_AUTH_NATIVE_CALLBACK_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_CALLBACK_LIMIT", "10")
)
ALLIES_AUTH_NATIVE_EXCHANGE_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_EXCHANGE_LIMIT", "10")
)
ALLIES_AUTH_NATIVE_REFRESH_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_REFRESH_LIMIT", "20")
)
ALLIES_AUTH_NATIVE_LOGOUT_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_LOGOUT_LIMIT", "30")
)
ALLIES_AUTH_NATIVE_ONBOARDING_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_ONBOARDING_LIMIT", "5")
)
ALLIES_AUTH_NATIVE_RATE_LIMIT_PERIOD_SECONDS = int(
    os.environ.get("ALLIES_AUTH_NATIVE_RATE_LIMIT_PERIOD_SECONDS", "60")
)
ALLIES_AUTH_NATIVE_GLOBAL_LIMIT = int(
    os.environ.get("ALLIES_AUTH_NATIVE_GLOBAL_LIMIT", "1000")
)

ALLIES_AVATAR_MAX_BYTES = int(
    os.environ.get("ALLIES_AVATAR_MAX_BYTES", str(5 * 1024 * 1024))
)
ALLIES_AVATAR_MAX_DIMENSION = int(os.environ.get("ALLIES_AVATAR_MAX_DIMENSION", "4096"))
ALLIES_AVATAR_MAX_PIXELS = int(os.environ.get("ALLIES_AVATAR_MAX_PIXELS", "16777216"))
ALLIES_AVATAR_URL_TTL_SECONDS = int(
    os.environ.get("ALLIES_AVATAR_URL_TTL_SECONDS", "300")
)
ALLIES_AVATAR_PENDING_TTL_SECONDS = int(
    os.environ.get("ALLIES_AVATAR_PENDING_TTL_SECONDS", str(24 * 60 * 60))
)
ALLIES_R2_ENDPOINT_URL = os.environ.get("ALLIES_R2_ENDPOINT_URL", "")
ALLIES_R2_BUCKET = os.environ.get("ALLIES_R2_BUCKET", "")
ALLIES_R2_ACCESS_KEY_ID = os.environ.get("ALLIES_R2_ACCESS_KEY_ID", "")
ALLIES_R2_SECRET_ACCESS_KEY = os.environ.get("ALLIES_R2_SECRET_ACCESS_KEY", "")
ALLIES_R2_ENABLED = env_bool("ALLIES_R2_ENABLED", False)

# Production dependency checks remain independent of the default-on feature flags.
ALLIES_FILE_ADMISSION_ENABLED = env_bool("ALLIES_FILE_ADMISSION_ENABLED", True)
ALLIES_FILE_STORAGE_ENABLED = env_bool("ALLIES_FILE_STORAGE_ENABLED", True)
ALLIES_FILE_STORAGE_ENDPOINT_URL = os.environ.get(
    "ALLIES_FILE_STORAGE_ENDPOINT_URL", ""
)
ALLIES_FILE_STORAGE_BUCKET = os.environ.get("ALLIES_FILE_STORAGE_BUCKET", "")
ALLIES_FILE_STORAGE_ACCESS_KEY_ID = os.environ.get(
    "ALLIES_FILE_STORAGE_ACCESS_KEY_ID", ""
)
ALLIES_FILE_STORAGE_SECRET_ACCESS_KEY = os.environ.get(
    "ALLIES_FILE_STORAGE_SECRET_ACCESS_KEY", ""
)
ALLIES_FILE_INSPECTION_ENABLED = env_bool("ALLIES_FILE_INSPECTION_ENABLED", True)

# Managed Gmail (provider-neutral passthrough, Gmail first). Grants default
# to none and sends require consent plus approval, so the rollout flag ships
# default-on; prod holds it False until Phase 6 evidences slice compatibility.
ALLIES_GMAIL_ENABLED = env_bool("ALLIES_GMAIL_ENABLED", True)
# Gmail reuses the sign-in Google client unless given its own full pair.
_gmail_client_id = os.environ.get("ALLIES_GMAIL_CLIENT_ID", "")
_gmail_client_secret = os.environ.get("ALLIES_GMAIL_CLIENT_SECRET", "")
if bool(_gmail_client_id) != bool(_gmail_client_secret):
    raise ImproperlyConfigured(
        "ALLIES_GMAIL_CLIENT_ID and ALLIES_GMAIL_CLIENT_SECRET must be set together"
    )
ALLIES_GMAIL_CLIENT_ID = _gmail_client_id or ALLIES_AUTH_GOOGLE_CLIENT_ID
ALLIES_GMAIL_CLIENT_SECRET = _gmail_client_secret or ALLIES_AUTH_GOOGLE_CLIENT_SECRET
ALLIES_GMAIL_REDIRECT_URI = os.environ.get("ALLIES_GMAIL_REDIRECT_URI", "")
ALLIES_FILE_SCANNER_HOST = os.environ.get("ALLIES_FILE_SCANNER_HOST", "")
ALLIES_FILE_SCANNER_PORT = env_bounded_int("ALLIES_FILE_SCANNER_PORT", 3310, 1, 65535)
ALLIES_FILE_INPUT_DELIVERY_ENABLED = env_bool(
    "ALLIES_FILE_INPUT_DELIVERY_ENABLED", True
)
ALLIES_FILE_STORAGE_CAPACITY_BYTES = int(
    os.environ.get("ALLIES_FILE_STORAGE_CAPACITY_BYTES", "10000000000")
)
if ALLIES_FILE_STORAGE_CAPACITY_BYTES < 0:
    raise ImproperlyConfigured(
        "ALLIES_FILE_STORAGE_CAPACITY_BYTES must not be negative"
    )
ALLIES_FILE_UPLOAD_LEASE_SECONDS = env_bounded_int(
    "ALLIES_FILE_UPLOAD_LEASE_SECONDS", 120, 1, 3600
)

CACHE_URL = os.environ.get("CACHE_URL", "")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_URL,
        "OPTIONS": {
            "socket_connect_timeout": CACHE_CONNECT_TIMEOUT_SECONDS,
            "socket_timeout": CACHE_SOCKET_TIMEOUT_SECONDS,
        },
    }
    if CACHE_URL
    else {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}
}
if CACHE_URL:
    # RedisCache serializes values with Django's binary serializer by default;
    # enabling redis-py's response decoding would corrupt those values before
    # Django can deserialize them.
    CACHES["health"] = {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_URL,
        "OPTIONS": {
            "decode_responses": False,
            "socket_connect_timeout": HEALTH_CACHE_OPERATION_TIMEOUT_SECONDS,
            "socket_timeout": HEALTH_CACHE_OPERATION_TIMEOUT_SECONDS,
        },
    }

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "")
if not CELERY_BROKER_URL:
    if CACHE_URL:
        parsed_cache_url = urlparse(CACHE_URL)
        CELERY_BROKER_URL = parsed_cache_url._replace(path="/1").geturl()
    else:
        CELERY_BROKER_URL = "redis://localhost:6379/1"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"
CELERY_TASK_DEFAULT_QUEUE = "cloud"
CELERY_TASK_IGNORE_RESULT = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_TASK_SOFT_TIME_LIMIT = 270
CELERY_TASK_TIME_LIMIT = 300
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    "cleanup-auth-artifacts": {
        "task": "auths.cleanup_auth_artifacts",
        "schedule": 900.0,
        "options": {"queue": "cloud"},
    }
}

ALLIES_ONBOARDING_ATTEMPT_TTL_SECONDS = env_positive_int(
    "ALLIES_ONBOARDING_ATTEMPT_TTL_SECONDS", 1800
)
ALLIES_FOUNDRY_URL = os.environ.get("ALLIES_FOUNDRY_URL", "")
ALLIES_FOUNDRY_SERVICE_TOKEN = os.environ.get("ALLIES_FOUNDRY_SERVICE_TOKEN", "")
ALLIES_FOUNDRY_TIMEOUT_SECONDS = env_positive_float(
    "ALLIES_FOUNDRY_TIMEOUT_SECONDS", 5.0
)
ALLIES_FOUNDRY_EVENT_SERVICE_TOKEN = os.environ.get(
    "ALLIES_FOUNDRY_EVENT_SERVICE_TOKEN", ""
)
ALLIES_FOUNDRY_EXECUTION_ENABLED = env_bool("ALLIES_FOUNDRY_EXECUTION_ENABLED", False)
ALLIES_VAULT_KEYS = os.environ.get("ALLIES_VAULT_KEYS", "")
ALLIES_CREDENTIAL_BROKER_TOKEN = os.environ.get("ALLIES_CREDENTIAL_BROKER_TOKEN", "")
ALLIES_ROUTINE_SCHEDULER_ENABLED = env_bool("ALLIES_ROUTINE_SCHEDULER_ENABLED", True)
ALLIES_ROUTINE_DISPATCH_ENABLED = env_bool("ALLIES_ROUTINE_DISPATCH_ENABLED", True)
ALLIES_ROUTINE_APPROVAL_ENABLED = env_bool("ALLIES_ROUTINE_APPROVAL_ENABLED", True)
ALLIES_ROUTINE_RESULT_INGESTION_ENABLED = env_bool(
    "ALLIES_ROUTINE_RESULT_INGESTION_ENABLED", True
)
ALLIES_ACTIVITY_SSE_ENABLED = env_bool("ALLIES_ACTIVITY_SSE_ENABLED", False)
# Keep provider transmission disabled until Foundry producer redaction evidence
# is recorded for every supported approval action kind.
ALLIES_APPROVAL_SUMMARIES_ENABLED = env_bool("ALLIES_APPROVAL_SUMMARIES_ENABLED", False)
ALLIES_RUNTIME_INTENT_ENABLED = env_bool("ALLIES_RUNTIME_INTENT_ENABLED", True)
ALLIES_RUNTIME_INTENT_RATE_LIMIT = env_bounded_int(
    "ALLIES_RUNTIME_INTENT_RATE_LIMIT", 20, 1, 120
)
ALLIES_RUNTIME_INTENT_RATE_PERIOD_SECONDS = env_bounded_int(
    "ALLIES_RUNTIME_INTENT_RATE_PERIOD_SECONDS", 60, 1, 3600
)
ALLIES_RUNTIME_INTENT_WORKSPACE_RATE_LIMIT = env_bounded_int(
    "ALLIES_RUNTIME_INTENT_WORKSPACE_RATE_LIMIT", 5, 1, 120
)
ALLIES_RUNTIME_INTENT_WORKSPACE_RATE_PERIOD_SECONDS = env_bounded_int(
    "ALLIES_RUNTIME_INTENT_WORKSPACE_RATE_PERIOD_SECONDS", 60, 1, 3600
)
ALLIES_RUNTIME_INTENT_DEDUPE_TTL_SECONDS = env_bounded_int(
    "ALLIES_RUNTIME_INTENT_DEDUPE_TTL_SECONDS", 600, 1, 3600
)
ALLIES_PROVISIONING_LEASE_SECONDS = env_positive_int(
    "ALLIES_PROVISIONING_LEASE_SECONDS", 60
)
ALLIES_PROVISIONING_MAX_BACKOFF_SECONDS = env_positive_int(
    "ALLIES_PROVISIONING_MAX_BACKOFF_SECONDS", 300
)
CELERY_BEAT_SCHEDULE["dispatch-due-provisioning"] = {
    "task": "allies.dispatch_due_provisioning",
    "schedule": 15.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["generate-pending-labels"] = {
    "task": "allies.generate_pending_labels",
    "schedule": 60.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["reconcile-due-ally-deletions"] = {
    "task": "allies.reconcile_due_ally_deletions",
    "schedule": 15.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["sync-model-selections"] = {
    "task": "model_keys.sync_selections",
    "schedule": 30.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["dispatch-pending-messages"] = {
    "task": "chat.dispatch_pending_messages",
    "schedule": 15.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["inspect-private-files"] = {
    "task": "files.inspect_due_files",
    "schedule": 30.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["cleanup-private-files"] = {
    "task": "files.cleanup_files",
    "schedule": 60.0,
    "options": {"queue": "cloud"},
}
CELERY_BEAT_SCHEDULE["dispatch-pending-approvals"] = {
    "task": "activities.dispatch_pending_approvals",
    "schedule": 15.0,
    "options": {"queue": "cloud"},
}
if ALLIES_ROUTINE_SCHEDULER_ENABLED:
    CELERY_BEAT_SCHEDULE["admit-due-routine-occurrences"] = {
        "task": "routines.admit_due_occurrences",
        "schedule": 15.0,
        "options": {"queue": "cloud"},
    }
if ALLIES_ROUTINE_DISPATCH_ENABLED:
    CELERY_BEAT_SCHEDULE["dispatch-pending-routine-outboxes"] = {
        "task": "routines.dispatch_pending_outboxes",
        "schedule": 15.0,
        "options": {"queue": "cloud"},
    }
if ALLIES_ROUTINE_APPROVAL_ENABLED:
    CELERY_BEAT_SCHEDULE["dispatch-pending-routine-approvals"] = {
        "task": "routines.dispatch_pending_approval_commands",
        "schedule": 15.0,
        "options": {"queue": "cloud"},
    }
    CELERY_BEAT_SCHEDULE["expire-routine-approvals"] = {
        "task": "routines.expire_approvals",
        "schedule": 60.0,
        "options": {"queue": "cloud"},
    }
CELERY_BEAT_SCHEDULE["cleanup-expired-onboarding-attempts"] = {
    "task": "allies.cleanup_expired_onboarding_attempts",
    "schedule": 900.0,
    "options": {"queue": "cloud"},
}

# CLD-008 Cloud waitlist preview.  The feature is deliberately disabled until
# staging has explicit provider, consent, origin, and retention decisions.
ALLIES_WAITLIST_ENABLED = env_bool("ALLIES_WAITLIST_ENABLED", False)
ALLIES_WAITLIST_TOKEN_KEY = os.environ.get("ALLIES_WAITLIST_TOKEN_KEY", "")
ALLIES_WAITLIST_ABANDONED_RETENTION_SECONDS = env_positive_int(
    "ALLIES_WAITLIST_ABANDONED_RETENTION_SECONDS", 7 * 24 * 60 * 60
)
_joined_retention_raw = os.environ.get("ALLIES_WAITLIST_JOINED_RETENTION_SECONDS", "")
try:
    ALLIES_WAITLIST_JOINED_RETENTION_SECONDS = (
        int(_joined_retention_raw) if _joined_retention_raw else None
    )
except ValueError as exc:
    raise ImproperlyConfigured(
        "ALLIES_WAITLIST_JOINED_RETENTION_SECONDS must be a positive integer"
    ) from exc
if ALLIES_WAITLIST_JOINED_RETENTION_SECONDS is not None and (
    ALLIES_WAITLIST_JOINED_RETENTION_SECONDS <= 0
):
    raise ImproperlyConfigured(
        "ALLIES_WAITLIST_JOINED_RETENTION_SECONDS must be positive when configured"
    )
ALLIES_WAITLIST_CONSENT_VERSION = os.environ.get("ALLIES_WAITLIST_CONSENT_VERSION", "")
ALLIES_WAITLIST_PROVIDER_ENABLED = env_bool("ALLIES_WAITLIST_PROVIDER_ENABLED", False)
ALLIES_WAITLIST_PROVIDER = os.environ.get("ALLIES_WAITLIST_PROVIDER", "openai")
ALLIES_WAITLIST_OPENAI_API_KEY = os.environ.get("ALLIES_WAITLIST_OPENAI_API_KEY", "")
_waitlist_model_configured = bool(os.environ.get("ALLIES_WAITLIST_OPENAI_MODEL", ""))
ALLIES_WAITLIST_OPENAI_MODEL = os.environ.get(
    "ALLIES_WAITLIST_OPENAI_MODEL", "gpt-4o-mini"
)
ALLIES_WAITLIST_OPENAI_URL = os.environ.get(
    "ALLIES_WAITLIST_OPENAI_URL", "https://api.openai.com/v1/responses"
)
ALLIES_WAITLIST_GENERATION_TIMEOUT_SECONDS = env_positive_float(
    "ALLIES_WAITLIST_GENERATION_TIMEOUT_SECONDS", 8.0
)
ALLIES_WAITLIST_GENERATION_MAX_OUTPUT_CHARS = env_positive_int(
    "ALLIES_WAITLIST_GENERATION_MAX_OUTPUT_CHARS", 1200
)
ALLIES_WAITLIST_GENERATION_GLOBAL_CONCURRENCY = env_positive_int(
    "ALLIES_WAITLIST_GENERATION_GLOBAL_CONCURRENCY", 4
)
ALLIES_WAITLIST_GENERATION_ATTEMPT_BUDGET_PER_MINUTE = env_positive_int(
    "ALLIES_WAITLIST_GENERATION_ATTEMPT_BUDGET_PER_MINUTE", 5
)


def _is_allowed_waitlist_provider_url(value: str) -> bool:
    parsed = urlparse(value)
    return (
        parsed.scheme == "https"
        and parsed.hostname == "api.openai.com"
        and parsed.path == "/v1/responses"
        and not parsed.params
        and not parsed.query
        and not parsed.fragment
    )


if ALLIES_WAITLIST_ENABLED and DEBUG:
    waitlist_debug_missing = []
    if not CACHE_URL:
        waitlist_debug_missing.append("CACHE_URL")
    if len(ALLIES_WAITLIST_TOKEN_KEY.encode()) < 32:
        waitlist_debug_missing.append("ALLIES_WAITLIST_TOKEN_KEY (at least 32 bytes)")
    if (
        ALLIES_WAITLIST_PROVIDER_ENABLED
        and ALLIES_WAITLIST_PROVIDER == "openai"
        and not _is_allowed_waitlist_provider_url(ALLIES_WAITLIST_OPENAI_URL)
    ):
        waitlist_debug_missing.append(
            "ALLIES_WAITLIST_OPENAI_URL=https://api.openai.com/v1/responses"
        )
    if waitlist_debug_missing:
        raise ImproperlyConfigured(
            "Unsafe CLD-008 production configuration: "
            + ", ".join(waitlist_debug_missing)
        )

if ALLIES_WAITLIST_ENABLED and not DEBUG:
    waitlist_missing = []
    if len(ALLIES_WAITLIST_TOKEN_KEY.encode()) < 32:
        waitlist_missing.append("ALLIES_WAITLIST_TOKEN_KEY (at least 32 bytes)")
    if not CACHE_URL:
        waitlist_missing.append("CACHE_URL")
    if not ALLIES_WAITLIST_CONSENT_VERSION:
        waitlist_missing.append("ALLIES_WAITLIST_CONSENT_VERSION")
    if ALLIES_WAITLIST_JOINED_RETENTION_SECONDS is None:
        waitlist_missing.append("ALLIES_WAITLIST_JOINED_RETENTION_SECONDS")
    if waitlist_missing:
        raise ImproperlyConfigured(
            "Unsafe CLD-008 production configuration: " + ", ".join(waitlist_missing)
        )

if ALLIES_WAITLIST_ENABLED:
    CELERY_BEAT_SCHEDULE["cleanup-waitlist-entries"] = {
        "task": "waitlist.cleanup_waitlist_entries",
        "schedule": 900.0,
        "options": {"queue": "cloud"},
    }

if not DEBUG:
    missing = []
    if ALLIES_AUTH_FAKE_PROVIDER_ENABLED:
        missing.append("ALLIES_AUTH_FAKE_PROVIDER_ENABLED must be false")
    if len(ALLIES_AUTH_JWT_KEY.encode()) < 32:
        missing.append("ALLIES_AUTH_JWT_KEY (at least 32 bytes)")
    if len(ALLIES_AUTH_DIGEST_KEY.encode()) < 32:
        missing.append("ALLIES_AUTH_DIGEST_KEY (at least 32 bytes)")
    if not CSRF_TRUSTED_ORIGINS:
        missing.append("ALLIES_TRUSTED_ORIGINS")
    if not ALLOWED_HOSTS:
        missing.append("DJANGO_ALLOWED_HOSTS")
    if not CACHE_URL:
        missing.append("CACHE_URL")
    if not DATABASE_URL:
        missing.append("PostgreSQL DATABASE_URL")
    if not ALLIES_WAITLIST_PROVIDER_ENABLED:
        missing.append("ALLIES_WAITLIST_PROVIDER_ENABLED=true for onboarding")
    if ALLIES_WAITLIST_PROVIDER != "openai":
        missing.append("ALLIES_WAITLIST_PROVIDER=openai")
    if not _is_allowed_waitlist_provider_url(ALLIES_WAITLIST_OPENAI_URL):
        missing.append("ALLIES_WAITLIST_OPENAI_URL=https://api.openai.com/v1/responses")
    if not ALLIES_WAITLIST_OPENAI_API_KEY:
        missing.append("ALLIES_WAITLIST_OPENAI_API_KEY")
    if not _waitlist_model_configured:
        missing.append("ALLIES_WAITLIST_OPENAI_MODEL")
    foundry_url = urlparse(ALLIES_FOUNDRY_URL)
    if foundry_url.scheme != "https" or not foundry_url.netloc:
        missing.append("HTTPS ALLIES_FOUNDRY_URL")
    if len(ALLIES_FOUNDRY_SERVICE_TOKEN) < 32 or any(
        character.isspace() for character in ALLIES_FOUNDRY_SERVICE_TOKEN
    ):
        missing.append("ALLIES_FOUNDRY_SERVICE_TOKEN (at least 32 bytes)")
    if ALLIES_FOUNDRY_EXECUTION_ENABLED and (
        len(ALLIES_FOUNDRY_EVENT_SERVICE_TOKEN) < 32
        or any(character.isspace() for character in ALLIES_FOUNDRY_EVENT_SERVICE_TOKEN)
    ):
        missing.append("ALLIES_FOUNDRY_EVENT_SERVICE_TOKEN (at least 32 bytes)")
    if ALLIES_CREDENTIAL_BROKER_TOKEN and (
        len(ALLIES_CREDENTIAL_BROKER_TOKEN) < 32
        or any(character.isspace() for character in ALLIES_CREDENTIAL_BROKER_TOKEN)
    ):
        missing.append("ALLIES_CREDENTIAL_BROKER_TOKEN (at least 32 bytes)")
    if (
        (
            ALLIES_TRUST_FORWARDED_PROTO
            or USE_X_FORWARDED_HOST
            or ALLIES_TRUST_FORWARDED_FOR
        )
        and not ALLIES_TRUSTED_PROXY_IPS
        and not ALLIES_RAILWAY_PROXY_MODE
    ):
        missing.append("ALLIES_TRUSTED_PROXY_IPS for forwarded-header trust")
    if ALLIES_AUTH_GOOGLE_ENABLED and not all(
        [
            ALLIES_AUTH_GOOGLE_CLIENT_ID,
            ALLIES_AUTH_GOOGLE_CLIENT_SECRET,
            ALLIES_AUTH_GOOGLE_REDIRECT_URI,
        ]
    ):
        missing.append("complete Google provider configuration")
    if ALLIES_AUTH_GOOGLE_ENABLED:
        google_redirect = urlparse(ALLIES_AUTH_GOOGLE_REDIRECT_URI)
        if (
            google_redirect.scheme != "https"
            or not google_redirect.netloc
            or google_redirect.username
            or google_redirect.password
            or google_redirect.params
            or google_redirect.query
            or google_redirect.fragment
        ):
            missing.append("HTTPS ALLIES_AUTH_GOOGLE_REDIRECT_URI")
    if ALLIES_AUTH_NATIVE_ENABLED:
        if not ALLIES_RAILWAY_PROXY_MODE:
            missing.append("ALLIES_RAILWAY_PROXY_MODE for native auth")
        if not ALLIES_AUTH_GOOGLE_ENABLED:
            missing.append("ALLIES_AUTH_GOOGLE_ENABLED for native auth")
        if not all(
            [
                ALLIES_AUTH_GOOGLE_CLIENT_ID,
                ALLIES_AUTH_GOOGLE_CLIENT_SECRET,
                ALLIES_AUTH_GOOGLE_REDIRECT_URI,
                ALLIES_AUTH_GOOGLE_NATIVE_REDIRECT_URI,
                ALLIES_AUTH_NATIVE_REDIRECT_URIS,
            ]
        ):
            missing.append(
                "complete native Google callback and app return configuration"
            )
        browser_callback = urlparse(ALLIES_AUTH_GOOGLE_REDIRECT_URI)
        native_callback = urlparse(ALLIES_AUTH_GOOGLE_NATIVE_REDIRECT_URI)
        if (
            browser_callback.scheme != "https"
            or native_callback.scheme != "https"
            or not native_callback.netloc
            or native_callback.username
            or native_callback.password
            or native_callback.params
            or native_callback.query
            or native_callback.fragment
            or ALLIES_AUTH_GOOGLE_NATIVE_REDIRECT_URI == ALLIES_AUTH_GOOGLE_REDIRECT_URI
            or native_callback.path != "/api/v1/auths/native/callback/google"
        ):
            missing.append("exact HTTPS native Google callback URI")
        for app_redirect in ALLIES_AUTH_NATIVE_REDIRECT_URIS:
            parsed = urlparse(app_redirect)
            if (
                not parsed.scheme
                or not parsed.netloc
                or parsed.username
                or parsed.password
                or parsed.params
                or parsed.query
                or parsed.fragment
                or "*" in app_redirect
                or parsed.scheme != "https"
            ):
                missing.append("exact HTTPS ALLIES_AUTH_NATIVE_REDIRECT_URIS")
                break
        native_lifetimes = (
            ALLIES_AUTH_NATIVE_TRANSACTION_TTL_SECONDS,
            ALLIES_AUTH_NATIVE_EXCHANGE_TTL_SECONDS,
            ALLIES_AUTH_NATIVE_PROVIDER_TIMEOUT_SECONDS,
            ALLIES_AUTH_NATIVE_CLAIM_LEASE_SECONDS,
            ALLIES_AUTH_NATIVE_TERMINAL_RETENTION_SECONDS,
            ALLIES_AUTH_NATIVE_SIGN_IN_LIMIT,
            ALLIES_AUTH_NATIVE_CALLBACK_LIMIT,
            ALLIES_AUTH_NATIVE_EXCHANGE_LIMIT,
            ALLIES_AUTH_NATIVE_REFRESH_LIMIT,
            ALLIES_AUTH_NATIVE_LOGOUT_LIMIT,
            ALLIES_AUTH_NATIVE_ONBOARDING_LIMIT,
            ALLIES_AUTH_NATIVE_RATE_LIMIT_PERIOD_SECONDS,
            ALLIES_AUTH_NATIVE_GLOBAL_LIMIT,
        )
        if any(value <= 0 for value in native_lifetimes):
            missing.append("positive native auth lifetimes and rate limits")
        if (
            ALLIES_AUTH_NATIVE_PROVIDER_TIMEOUT_SECONDS
            >= ALLIES_AUTH_NATIVE_CLAIM_LEASE_SECONDS
        ):
            missing.append(
                "native provider timeout must be less than native claim lease"
            )
    if ALLIES_R2_ENABLED and not all(
        [
            ALLIES_R2_ENDPOINT_URL,
            ALLIES_R2_BUCKET,
            ALLIES_R2_ACCESS_KEY_ID,
            ALLIES_R2_SECRET_ACCESS_KEY,
        ]
    ):
        missing.append("complete R2 configuration")
    if ALLIES_R2_ENABLED:
        r2_endpoint = urlparse(ALLIES_R2_ENDPOINT_URL)
        if r2_endpoint.scheme != "https" or not r2_endpoint.netloc:
            missing.append("HTTPS ALLIES_R2_ENDPOINT_URL")
    if ALLIES_FILE_ADMISSION_ENABLED and not ALLIES_FILE_STORAGE_ENABLED:
        missing.append("ALLIES_FILE_STORAGE_ENABLED for file admission")
    if ALLIES_FILE_INSPECTION_ENABLED and not ALLIES_FILE_SCANNER_HOST.strip():
        missing.append("ALLIES_FILE_SCANNER_HOST for file inspection")
    if ALLIES_FILE_ADMISSION_ENABLED and ALLIES_FILE_STORAGE_CAPACITY_BYTES <= 0:
        missing.append("positive ALLIES_FILE_STORAGE_CAPACITY_BYTES for file admission")
    if ALLIES_FILE_STORAGE_ENABLED and not all(
        [
            ALLIES_FILE_STORAGE_ENDPOINT_URL,
            ALLIES_FILE_STORAGE_BUCKET,
            ALLIES_FILE_STORAGE_ACCESS_KEY_ID,
            ALLIES_FILE_STORAGE_SECRET_ACCESS_KEY,
        ]
    ):
        missing.append("complete private file storage configuration")
    if ALLIES_FILE_STORAGE_ENABLED:
        file_endpoint = urlparse(ALLIES_FILE_STORAGE_ENDPOINT_URL)
        if file_endpoint.scheme != "https" or not file_endpoint.netloc:
            missing.append("HTTPS ALLIES_FILE_STORAGE_ENDPOINT_URL")
    if missing:
        raise ImproperlyConfigured(
            "Unsafe AUTH-001 production configuration: " + ", ".join(missing)
        )
