# Generated by Django 6.0.7 on 2026-09-09 07:16
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_approval_explanation"),
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0006_routinedispatchoutbox_attempt_id_and_more"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineResultProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(editable=False, unique=True)),
                ("event_sequence", models.PositiveIntegerField()),
                ("routine_revision", models.PositiveIntegerField()),
                ("execution_id", models.UUIDField()),
                ("attempt_id", models.UUIDField()),
                ("generation", models.PositiveIntegerField()),
                ("main_conversation_id", models.UUIDField()),
                ("run_conversation_id", models.UUIDField()),
                ("title_snapshot", models.CharField(max_length=120)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("changed", "Changed"),
                            ("unchanged", "Unchanged"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(max_length=16384)),
                ("references", models.JSONField(default=list)),
                ("delayed", models.BooleanField(default=False)),
                ("issued_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField()),
                ("fingerprint", models.CharField(max_length=90)),
                (
                    "insertion_state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("inserted", "Inserted")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "insertion_watermark",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("inserted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_result_projections",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_result_projections",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_projections",
                        to="routines.routineoccurrence",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_result_projections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_projections",
                        to="routines.routine",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_projection",
                        to="routines.routinerunsnapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_result_projections",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RoutineResultReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(editable=False, unique=True)),
                ("event_sequence", models.PositiveIntegerField()),
                ("disposition", models.CharField(default="applied", max_length=16)),
                (
                    "result_insertion",
                    models.CharField(
                        choices=[("pending", "Pending"), ("inserted", "Inserted")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "insertion_watermark",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="activities.routineresultprojection",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="routineresultprojection",
            index=models.Index(
                fields=["main_conversation_id", "insertion_state", "created_at"],
                name="routine_result_insert_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routineresultprojection",
            index=models.Index(
                fields=["workspace", "owner", "created_at"],
                name="routine_result_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineresultprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event_sequence__gt", 0),
                    ("routine_revision__gt", 0),
                    models.Q(
                        ("main_conversation_id", models.F("run_conversation_id")),
                        _negated=True,
                    ),
                    models.Q(
                        models.Q(
                            ("inserted_at__isnull", False),
                            ("insertion_state", "inserted"),
                            ("insertion_watermark__isnull", False),
                        ),
                        models.Q(
                            ("inserted_at__isnull", True),
                            ("insertion_state", "pending"),
                            ("insertion_watermark__isnull", True),
                        ),
                        _connector="OR",
                    ),
                ),
                name="routine_result_state_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineresultprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fingerprint__regex", "^canonical-json-sha256:v1:[0-9a-f]{64}$")
                ),
                name="routine_result_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineresultreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_sequence__gt", 0)),
                name="routine_result_receipt_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineresultreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("insertion_watermark__isnull", False),
                        ("result_insertion", "inserted"),
                    ),
                    models.Q(
                        ("insertion_watermark__isnull", True),
                        ("result_insertion", "pending"),
                    ),
                    _connector="OR",
                ),
                name="routine_result_receipt_state_coherent",
            ),
        ),
    ]
