# Generated by Django 6.0.7 on 2026-09-25 22:41
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_routine_result_context"),
        ("chat", "0011_merge_20260910_1653"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundryHeldEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("attempt_id", models.UUIDField()),
                ("generation", models.PositiveIntegerField()),
                ("attempt_sequence", models.PositiveIntegerField()),
                ("event_fingerprint", models.CharField(max_length=90)),
                ("envelope", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foundry_held_events",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "message",
                            "attempt_id",
                            "generation",
                            "attempt_sequence",
                        ),
                        name="activities_held_event_sequence_uniq",
                    )
                ],
            },
        ),
    ]
