# Generated by Django 6.0.7 on 2026-08-31 14:28
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_dispatchoutbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retry_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="chat.message",
            ),
        ),
    ]
