# Generated by Django 6.0.7 on 2026-09-04 22:35
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_retry_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retry_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(retry_allowed=False)
                | models.Q(sender="user", origin="send", status="failed"),
                name="chat_message_retry_safe_chk",
            ),
        ),
        migrations.CreateModel(
            name="AssistantReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("has_full_prefix", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_reply",
                        to="chat.message",
                    ),
                ),
            ],
        ),
    ]
