# Generated by Django 6.0.7 on 2026-09-05
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_durable_assistant_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantreply",
            name="is_truncated",
            field=models.BooleanField(default=False),
        ),
    ]
