# Generated by Django 6.0.7 on 2026-09-06
# ruff: noqa: RUF012

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone

_NONTERMINAL = ("queued", "in_progress", "awaiting_action")


def mark_legacy_claims(apps, schema_editor):
    del schema_editor
    Message = apps.get_model("chat", "Message")
    DispatchOutbox = apps.get_model("chat", "DispatchOutbox")
    FoundryEventReceipt = apps.get_model("activities", "FoundryEventReceipt")
    now = timezone.now()
    live = Message.objects.filter(
        sender="user",
        origin="send",
        status__in=_NONTERMINAL,
        deleted_at__isnull=True,
    )
    # No receipt is not proof of no execution. Only a never-acquired fence or
    # a first-fence error unique to the pre-call path proves safe terminality.
    proven_pre_call = DispatchOutbox.objects.filter(
        Q(attempt_count=0, last_attempt_at__isnull=True)
        | Q(
            attempt_count=1,
            safe_error_code__in=(
                "binding_incompatible",
                "onboarding_handoff_unavailable",
                "onboarding_handoff_repair_required",
            ),
        ),
        status="failed",
        receipt_digest="",
        message__in=live,
    ).exclude(message_id__in=FoundryEventReceipt.objects.values("message_id"))
    Message.objects.filter(pk__in=proven_pre_call.values("message_id")).update(
        status="failed", retry_allowed=False, execution_claimed_at=None
    )
    attempted = DispatchOutbox.objects.filter(
        Q(last_attempt_at__isnull=False)
        | ~Q(status="pending")
        | Q(attempt_count__gt=0),
        message__in=live,
    ).values_list("message_id", flat=True)
    Message.objects.filter(pk__in=attempted, execution_claimed_at__isnull=True).update(
        execution_claimed_at=now
    )

    for conversation_id in (
        live.filter(execution_claimed_at__isnull=True)
        .values_list("conversation_id", flat=True)
        .distinct()
    ):
        if live.filter(
            conversation_id=conversation_id,
            execution_claimed_at__isnull=False,
        ).exists():
            continue
        first = (
            Message.objects.filter(
                conversation_id=conversation_id,
                sender="user",
                origin="send",
                status__in=_NONTERMINAL,
                deleted_at__isnull=True,
                execution_claimed_at__isnull=True,
            )
            .order_by("sequence", "id")
            .first()
        )
        if (
            first is not None
            and DispatchOutbox.objects.filter(message_id=first.pk).exists()
        ):
            Message.objects.filter(
                pk=first.pk, execution_claimed_at__isnull=True
            ).update(execution_claimed_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_assistantreply_is_truncated"),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="execution_claimed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(mark_legacy_claims, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(execution_claimed_at__isnull=True)
                    | models.Q(sender="user", origin="send")
                ),
                name="chat_message_claim_scope_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(deleted_at__isnull=True)
                    | models.Q(
                        sender="user",
                        origin="send",
                        status="stopped",
                        execution_claimed_at__isnull=True,
                        content="",
                    )
                ),
                name="chat_message_tombstone_coherent_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "sequence"],
                condition=models.Q(
                    sender="user",
                    origin="send",
                    status__in=_NONTERMINAL,
                    deleted_at__isnull=True,
                ),
                name="chat_message_queue_idx",
            ),
        ),
    ]
