# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chat", "0006_message_queue_claims")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="preparation",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("uploading", "Uploading"),
                    ("failed", "Failed"),
                    ("needs_retry", "Needs retry"),
                    ("ready", "Ready"),
                    ("cancelled", "Cancelled"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="preparation_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="send_armed",
            field=models.BooleanField(default=False),
        ),
    ]
