# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_message_client_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="routine_action",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
