# Generated by Django 6.0.7 on 2026-09-09 23:12
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_message_file_preparation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchoutbox",
            name="file_manifest",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
