# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chat", "0009_message_foundry_binding")]

    operations = [
        migrations.AddField(
            model_name="assistantreply",
            name="pending_file_reference",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=44
            ),
        )
    ]
