# ruff: noqa: RUF012
# Generated by Django 6.0.7 on 2026-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_message_routine_action"),
        ("chat", "0010_assistantreply_pending_file_reference"),
    ]

    operations = []
