# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ally",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="ally",
            name="show_label",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ally",
            name="settings_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ally",
            name="label_generation_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("claimed", "Claimed"),
                    ("complete", "Complete"),
                    ("unavailable", "Unavailable"),
                ],
                default="unavailable",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="ally",
            index=models.Index(
                fields=["label_generation_state", "updated_at"],
                name="ally_label_state_updated_idx",
            ),
        ),
    ]
