# Generated by Django 6.0.7 on 2026-09-10 22:50
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import allies.models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0004_ally_label_settings"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllyDeletionMarker",
            fields=[
                (
                    "ally_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeletionOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ally_id", models.UUIDField(editable=False)),
                ("binding_id", models.UUIDField(editable=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("repair_required", "Repair required"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("foundry", "Foundry cleanup"),
                            ("files", "File cleanup"),
                            ("purge", "Relational purge"),
                        ],
                        default="foundry",
                        max_length=16,
                    ),
                ),
                ("attempt_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "supersedes_attempt_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "lifecycle_epoch",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(default=0, editable=False),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=allies.models.default_deletion_expiry),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "foundry_state",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "foundry_attempt_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "foundry_resume_attempt_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "foundry_receipt_id",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=128
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="ally",
            name="deletion_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending deletion"),
                    ("repair_required", "Deletion needs repair"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="ally",
            index=models.Index(
                fields=["workspace", "deletion_state", "id"],
                name="ally_workspace_deletion_idx",
            ),
        ),
        migrations.AddField(
            model_name="allydeletionmarker",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ally_deletion_markers",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="deletionoperation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ally_deletion_operations",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="allydeletionmarker",
            index=models.Index(
                fields=["workspace", "ally_id"], name="ally_deletion_marker_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deletionoperation",
            index=models.Index(
                fields=["state", "next_attempt_at", "lease_expires_at", "id"],
                name="allies_deletion_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deletionoperation",
            index=models.Index(
                fields=["workspace", "ally_id"], name="allies_deletion_identity_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "ally_id"), name="allies_deletion_scope_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle_epoch__gt", 0)),
                name="allies_deletion_epoch_positive",
            ),
        ),
    ]
