# Generated by Django 6.0.7 on 2026-09-25 08:24
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("allies", "0005_ally_deletion"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_key", models.CharField(max_length=32)),
                ("account_ref_hash", models.CharField(max_length=64)),
                ("account_email", models.CharField(default="", max_length=254)),
                ("ciphertext", models.BinaryField()),
                ("key_version", models.PositiveIntegerField(default=1)),
                ("scope_set", models.JSONField(default=list)),
                ("generation_epoch", models.PositiveIntegerField(default=1)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_secrets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllyIntegrationGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.CharField(max_length=8)),
                ("grant_generation", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_grants",
                        to="allies.ally",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_integration_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ally_grants",
                        to="integrations.integrationsecret",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GmailConnectSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("sealed_handshake", models.TextField()),
                ("entry_point", models.CharField(max_length=16)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ally",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_connect_sessions",
                        to="allies.ally",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_connect_sessions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="gmail_conn_ws_created_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="integrationsecret",
            index=models.Index(
                fields=["workspace", "provider_key"], name="int_secret_ws_provider_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationsecret",
            constraint=models.UniqueConstraint(
                fields=("workspace", "provider_key", "account_ref_hash"),
                name="integration_secret_workspace_provider_account_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("workspace", "provider_key"),
                name="integration_secret_one_active_provider_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="allyintegrationgrant",
            constraint=models.UniqueConstraint(
                fields=("secret", "ally"),
                name="ally_integration_grant_secret_ally_uniq",
            ),
        ),
    ]
