# Generated by Django 6.0.7 on 2026-09-25 08:14
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsecret",
            name="generation_epoch",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="integrationsecret",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("workspace", "provider_key"),
                name="integration_secret_one_active_provider_uniq",
            ),
        ),
    ]
