# Generated by Django 6.0.7 on 2026-09-25 21:22
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_merge_20260910_1653"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                (
                    "consumed_ref",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.message"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "call_id"), name="integration_tool_call_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("consumed_ref",), name="integration_tool_ref_uniq"
                    ),
                ],
            },
        ),
    ]
