# Generated by Django 6.0.7 on 2026-09-09 03:45
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_conversation_id", models.UUIDField()),
                ("title", models.CharField(max_length=120)),
                ("execution_prompt", models.TextField(max_length=16384)),
                ("schedule", models.JSONField()),
                ("revision", models.PositiveIntegerField(default=1)),
                ("schedule_generation", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("deleted", "Deleted"),
                            ("exhausted", "Exhausted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("resume_boundary", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routines",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routines",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routines",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["workspace", "owner", "state", "created_at"],
                        name="routine_owner_state_idx",
                    ),
                    models.Index(
                        fields=["state", "next_run_at"],
                        name="routine_state_next_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="routine_revision_positive_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schedule_generation__gt", 0)),
                        name="routine_generation_positive_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deleted_at__isnull", False), ("state", "deleted")
                            ),
                            models.Q(("state", "deleted"), _negated=True),
                            _connector="OR",
                        ),
                        name="routine_deleted_state_coherent_chk",
                    ),
                ],
            },
        ),
    ]
