# Generated by Django 6.0.7 on 2026-09-09 07:39
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0005_routineoccurrence_routinerunsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinedispatchoutbox",
            name="attempt_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="routinedispatchoutbox",
            name="execution_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="routinedispatchoutbox",
            name="generation",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "accepted"), _negated=True),
                    models.Q(
                        ("execution_id__isnull", False),
                        ("attempt_id__isnull", False),
                        ("generation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="routine_dispatch_accept_identity_chk",
            ),
        ),
    ]
