# Generated by Django 6.0.7 on 2026-09-10 07:38
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_message_queue_claims"),
        ("routines", "0008_routineapprovalprojection_routineapprovalcommand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.message"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "call_id"),
                        name="routine_tool_message_call_uniq",
                    )
                ],
            },
        ),
    ]
