"""Version-one private-file type policy without application credentials."""

MAX_FILE_BYTES = 25_000_000

MEDIA_TYPES = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "gif": "image/gif",
    "webp": "image/webp",
    "heic": "image/heic",
    "heif": "image/heif",
    "pdf": "application/pdf",
    "doc": "application/msword",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "xls": "application/vnd.ms-excel",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "csv": "text/csv",
    "ppt": "application/vnd.ms-powerpoint",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "txt": "text/plain",
    "md": "text/markdown",
    "markdown": "text/markdown",
    "json": "application/json",
    "html": "text/html",
    "htm": "text/html",
    "css": "text/css",
    "xml": "application/xml",
    "yaml": "application/yaml",
    "yml": "application/yaml",
    "toml": "application/toml",
    "js": "text/javascript",
    "jsx": "text/javascript",
    "ts": "text/plain",
    "tsx": "text/plain",
    "py": "text/plain",
    "rb": "text/plain",
    "go": "text/plain",
    "rs": "text/plain",
    "java": "text/plain",
    "c": "text/plain",
    "h": "text/plain",
    "cpp": "text/plain",
    "hpp": "text/plain",
    "cs": "text/plain",
    "sh": "text/plain",
    "sql": "text/plain",
}
