# Generated by Django 6.0.7 on 2026-09-04 00:26
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="runtime_intent_mode",
            field=models.CharField(
                choices=[("off", "Off"), ("composing", "Composing"), ("open", "Open")],
                default="off",
                max_length=16,
            ),
        ),
    ]
