# Generated by Django 6.0.7 on 2026-09-27 15:58
# ruff: noqa: RUF012

from django.db import migrations, models


def wake_existing_workspaces_early(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    Workspace.objects.filter(runtime_intent_mode="off").update(
        runtime_intent_mode="composing"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_runtime_intent_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="runtime_intent_mode",
            field=models.CharField(
                choices=[("off", "Off"), ("composing", "Composing"), ("open", "Open")],
                default="composing",
                max_length=16,
            ),
        ),
        migrations.RunPython(wake_existing_workspaces_early, migrations.RunPython.noop),
    ]
