# ruff: noqa: RUF012
# Generated by Django 6.0.7 on 2026-09-25 21:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("allies", "0005_ally_deletion"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("ciphertext", models.BinaryField()),
                ("key_hint", models.CharField(max_length=4)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_keys",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllyModelSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("foundry_profile_id", models.UUIDField()),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("reasoning", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("connected", "Connected"),
                            ("degraded", "Needs attention"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("synced", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("sync_attempts", models.PositiveSmallIntegerField(default=0)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_selection",
                        to="allies.ally",
                    ),
                ),
                (
                    "model_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="model_keys.modelkey",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("workspace", "provider"),
                name="model_key_one_active_per_provider",
            ),
        ),
        migrations.AddIndex(
            model_name="allymodelselection",
            index=models.Index(
                fields=["synced", "updated_at"], name="model_selection_sync_idx"
            ),
        ),
    ]
