# Generated by Django 6.0.7 on 2026-08-26 01:07
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0002_dispatchoutbox_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("conversation_turn_ordinal", models.PositiveIntegerField()),
                ("generation", models.PositiveIntegerField()),
                ("attempt_id", models.UUIDField()),
                ("attempt_sequence", models.PositiveIntegerField()),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=64)),
                ("text", models.TextField(blank=True, default="", max_length=16000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("awaiting_action", "Awaiting action"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                            ("reconciliation_needed", "Reconciliation needed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_fingerprint", models.CharField(max_length=90)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
                "indexes": [
                    models.Index(
                        fields=[
                            "conversation",
                            "conversation_turn_ordinal",
                            "sequence",
                        ],
                        name="activities_conv_turn_idx",
                    ),
                    models.Index(
                        fields=["message", "generation", "attempt_sequence"],
                        name="activities_message_attempt_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"),
                        name="activities_conversation_sequence_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("message", "attempt_id", "event_id"),
                        name="activities_event_identity_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("message", "attempt_id", "attempt_sequence"),
                        name="activities_attempt_sequence_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sequence__gt", 0),
                            ("conversation_turn_ordinal__gt", 0),
                            ("generation__gte", 0),
                            ("attempt_sequence__gt", 0),
                        ),
                        name="activities_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_fingerprint__regex",
                                "^canonical-json-sha256:v1:[0-9a-f]{64}$",
                            )
                        ),
                        name="activities_fingerprint_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FoundryEventReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("execution_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("event_dedupe_key", models.CharField(max_length=255)),
                ("attempt_id", models.UUIDField()),
                ("generation", models.PositiveIntegerField()),
                ("attempt_sequence", models.PositiveIntegerField()),
                ("event_fingerprint", models.CharField(max_length=90)),
                (
                    "result",
                    models.CharField(choices=[("applied", "Applied")], max_length=16),
                ),
                (
                    "product_sequence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foundry_event_receipts",
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foundry_event_receipts",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["message", "generation", "attempt_sequence"],
                        name="activities_receipt_order_idx",
                    ),
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="activities_receipt_conv_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "attempt_id", "event_id"),
                        name="activities_receipt_event_identity_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("message", "attempt_id", "attempt_sequence"),
                        name="activities_receipt_attempt_sequence_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("generation__gte", 0), ("attempt_sequence__gt", 0)
                        ),
                        name="activities_receipt_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_fingerprint__regex",
                                "^canonical-json-sha256:v1:[0-9a-f]{64}$",
                            )
                        ),
                        name="activities_receipt_fingerprint_valid",
                    ),
                ],
            },
        ),
    ]
