# Generated by Django 6.0.7 on 2026-09-08 00:41

from django.db import migrations, models

# Django migration declarations intentionally use mutable class collections.
# ruff: noqa: RUF012


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundryeventreceipt",
            name="activity_id",
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
        migrations.AddField(
            model_name="foundryeventreceipt",
            name="activity_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="foundryeventreceipt",
            name="outcome",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_id",
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="outcome",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
