"""Initial durable approval model and generic activity relation."""

# Generated by Django 6.0.7 on 2026-09-08 04:32
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_activity_activity_id_activity_activity_kind_and_more"),
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("chat", "0006_message_queue_claims"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("approval_request_id", models.UUIDField(editable=False, unique=True)),
                ("cloud_binding_id", models.UUIDField(editable=False)),
                ("execution_id", models.UUIDField(editable=False)),
                ("attempt_id", models.UUIDField(editable=False)),
                ("generation", models.PositiveIntegerField()),
                ("attempt_sequence", models.PositiveIntegerField()),
                ("action_kind", models.CharField(max_length=64)),
                ("action_label", models.CharField(max_length=120)),
                ("action_preview", models.TextField(max_length=16384)),
                ("requested_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("decision_recorded", "Decision recorded"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("decision", models.CharField(blank=True, default="", max_length=7)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgement_deadline_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "decision_idempotency_key",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "decision_idempotency_key_digest",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "decision_fingerprint",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=90
                    ),
                ),
                (
                    "delivery_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "delivery_next_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "delivery_lease_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "delivery_last_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("delivery_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "delivery_receipt_digest",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="allies.ally",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="chat.conversation",
                    ),
                ),
                (
                    "deciding_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="chat.message",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="activities.approval",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["conversation", "status", "expires_at"],
                name="activities_appr_conv_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=[
                    "delivery_state",
                    "delivery_next_attempt_at",
                    "delivery_lease_expires_at",
                ],
                name="activities_appr_delivery_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("generation__gte", 0),
                    ("attempt_sequence__gt", 0),
                    ("delivery_attempt_count__gte", 0),
                    ("delivery_attempt_count__lte", 5),
                ),
                name="activities_approval_sequence_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action_label__regex", "^[^\\x00]*$"),
                    models.Q(("action_label", ""), _negated=True),
                    ("action_preview__regex", "^[^\\x00]*$"),
                    models.Q(("action_preview", ""), _negated=True),
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.functions.text.Length("action_preview"),
                        "<=",
                        models.Value(16384),
                        output_field=models.BooleanField(),
                    ),
                ),
                name="activities_approval_material_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision_fingerprint", ""),
                    (
                        "decision_fingerprint__regex",
                        "^canonical-json-sha256:v1:[0-9a-f]{64}$",
                    ),
                    _connector="OR",
                ),
                name="activities_approval_decision_fingerprint_valid",
            ),
        ),
    ]
