# ruff: noqa: RUF012
# Generated by Django 6.0.7 on 2026-09-29 21:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0007_foundry_held_event"),
        ("allies", "0005_ally_deletion"),
        ("auths", "0003_beta_invites"),
        ("chat", "0011_merge_20260910_1653"),
        ("routines", "0010_routine_source_message"),
        ("workspaces", "0003_early_wake_by_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity", models.CharField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approval_needed", "approval_needed"),
                            ("routine_completed", "routine_completed"),
                            ("routine_failed", "routine_failed"),
                            ("reply_completed", "reply_completed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="allies.ally"
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.approval",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.conversation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.assistantreply",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.routineresultprojection",
                    ),
                ),
                (
                    "routine_approval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routines.routineapprovalprojection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("browser_id", models.UUIDField()),
                ("binding_id", models.UUIDField(unique=True)),
                ("registration_digest", models.CharField(max_length=64)),
                ("endpoint_digest", models.CharField(max_length=64)),
                ("secret", models.BinaryField(default=bytes)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("presence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auths.sessionfamily",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("binding_id", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("suppressed", "suppressed"),
                            ("retired", "retired"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("lease_until", models.DateTimeField(null=True)),
                ("safe_error_code", models.CharField(blank=True, max_length=40)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.pushnotification",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.pushsubscription",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pushsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("endpoint_digest",),
                name="push_active_endpoint_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pushsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("owner", "browser_id"),
                name="push_active_browser_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.UniqueConstraint(
                fields=("subscription", "notification"), name="push_delivery_pair_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", 3)), name="push_attempts_bounded"
            ),
        ),
    ]
