# Generated by Django 6.0.7 on 2026-08-11 17:44
# ruff: noqa: RUF012

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import auths.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ("public_id",),
            },
            managers=[
                ("objects", auths.models.ActorManager()),
            ],
        ),
        migrations.CreateModel(
            name="AvatarAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "object_key",
                    models.CharField(editable=False, max_length=500, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("replaced", "Replaced"),
                            ("deleted", "Deleted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expected_content_type", models.CharField(max_length=64)),
                ("expected_size", models.PositiveIntegerField()),
                ("expected_sha256", models.CharField(max_length=64)),
                ("actual_content_type", models.CharField(blank=True, max_length=64)),
                ("actual_size", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_sha256", models.CharField(blank=True, max_length=64)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_attempts", models.PositiveIntegerField(default=0)),
                ("cleanup_last_error", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")], max_length=32
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("display_name_snapshot", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("idle_expires_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="auths.sessionfamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("flow_cookie_digest", models.CharField(editable=False, max_length=64)),
                (
                    "browser_binding_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")], max_length=32
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("sign_in", "Sign in"), ("link", "Link identity")],
                        max_length=16,
                    ),
                ),
                ("redirect_to", models.CharField(max_length=500)),
                ("callback_uri", models.CharField(max_length=500)),
                ("nonce_digest", models.CharField(editable=False, max_length=64)),
                ("nonce_sealed", models.TextField(editable=False)),
                ("pkce_verifier_sealed", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_flows",
                        to="auths.sessionfamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_for_profiles",
                        to="auths.avatarasset",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(
                fields=["is_active", "public_id"], name="auth_actor_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avatarasset",
            index=models.Index(
                fields=["actor", "created_at"], name="auth_avatar_actor_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="avatarasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size__gt", 0)),
                name="auth_avatar_expected_size_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="avatarasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_sha256__regex", "^[0-9a-fA-F]{64}$")),
                name="auth_avatar_expected_sha_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(
                fields=["actor", "provider"], name="auth_identity_actor_prov_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"),
                name="auth_identity_provider_subject_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionfamily",
            index=models.Index(fields=["actor"], name="auth_family_actor_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionfamily",
            index=models.Index(
                fields=["revoked_at", "absolute_expires_at", "idle_expires_at"],
                name="auth_family_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["family", "expires_at"], name="auth_refresh_family_expiry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("family",),
                name="auth_refresh_one_unused_per_family_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="authflow",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_flow_expiry_consumed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="authflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor__isnull", True),
                        ("purpose", "sign_in"),
                        ("session_family__isnull", True),
                    ),
                    models.Q(
                        ("actor__isnull", False),
                        ("purpose", "link"),
                        ("session_family__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="auth_flow_purpose_binding_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_name__isnull", False)),
                name="auth_profile_display_name_not_null",
            ),
        ),
    ]
