# Generated by Django 6.0.7 on 2026-08-25 23:03
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import auths.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            managers=[
                ("objects", auths.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AvatarAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(editable=False, max_length=500, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("replaced", "Replaced"),
                            ("deleted", "Deleted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expected_content_type", models.CharField(max_length=64)),
                ("expected_size", models.PositiveIntegerField()),
                ("expected_sha256", models.CharField(max_length=64)),
                ("actual_content_type", models.CharField(blank=True, max_length=64)),
                ("actual_size", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_sha256", models.CharField(blank=True, max_length=64)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_attempts", models.PositiveIntegerField(default=0)),
                ("cleanup_last_error", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")], max_length=32
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verification_source",
                    models.CharField(blank=True, max_length=32),
                ),
                ("display_name_snapshot", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NativeAuthorizationTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")], max_length=32
                    ),
                ),
                ("callback_uri", models.CharField(max_length=500)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("app_state_sealed", models.TextField(editable=False)),
                ("code_challenge", models.CharField(editable=False, max_length=128)),
                ("nonce_digest", models.CharField(editable=False, max_length=64)),
                ("nonce_sealed", models.TextField(editable=False)),
                ("pkce_verifier_sealed", models.TextField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "claim_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="auth_native_tx_state_exp_idx",
                    ),
                    models.Index(
                        fields=["status", "claim_expires_at"],
                        name="auth_native_tx_claim_exp_idx",
                    ),
                    models.Index(
                        fields=["status", "terminal_at"],
                        name="auth_native_tx_terminal_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "pending"), ("terminal_at__isnull", True)
                            ),
                            models.Q(
                                ("claim_expires_at__isnull", False),
                                ("claimed_at__isnull", False),
                                ("status", "claimed"),
                                ("terminal_at__isnull", True),
                            ),
                            models.Q(
                                ("status__in", ("completed", "denied", "failed")),
                                ("terminal_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="auth_native_tx_status_coherent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NativeExchangeCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("code_sealed", models.TextField(editable=False)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("code_challenge", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_code",
                        to="auths.nativeauthorizationtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_exchange_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("idle_expires_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=64)),
                (
                    "client_kind",
                    models.CharField(
                        choices=[("browser", "Browser"), ("native", "Native")],
                        default="browser",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="auths.sessionfamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("flow_cookie_digest", models.CharField(editable=False, max_length=64)),
                (
                    "browser_binding_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")], max_length=32
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("sign_in", "Sign in"), ("link", "Link identity")],
                        max_length=16,
                    ),
                ),
                ("redirect_to", models.CharField(max_length=500)),
                ("callback_uri", models.CharField(max_length=500)),
                ("nonce_digest", models.CharField(editable=False, max_length=64)),
                ("nonce_sealed", models.TextField(editable=False)),
                ("pkce_verifier_sealed", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_flows",
                        to="auths.sessionfamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_for_profiles",
                        to="auths.avatarasset",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active", "id"], name="auth_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="avatarasset",
            index=models.Index(
                fields=["user", "created_at"], name="auth_avatar_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="avatarasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size__gt", 0)),
                name="auth_avatar_expected_size_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="avatarasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_sha256__regex", "^[0-9a-fA-F]{64}$")),
                name="auth_avatar_expected_sha_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(
                fields=["user", "provider"], name="auth_identity_user_prov_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"),
                name="auth_identity_provider_subject_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("email_verification_source", ""),
                        ("email_verified", False),
                        ("email_verified_at__isnull", True),
                    ),
                    models.Q(
                        ("email_snapshot__gt", ""),
                        ("email_verification_source", "google"),
                        ("email_verified", True),
                        ("email_verified_at__isnull", False),
                        ("provider", "google"),
                    ),
                    _connector="OR",
                ),
                name="auth_identity_verified_email_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="nativeexchangecode",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_native_code_exp_cons_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionfamily",
            index=models.Index(fields=["user"], name="auth_family_user_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionfamily",
            index=models.Index(
                fields=["revoked_at", "absolute_expires_at", "idle_expires_at"],
                name="auth_family_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["family", "expires_at"], name="auth_refresh_family_expiry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("family",),
                name="auth_refresh_one_unused_per_family_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="authflow",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_flow_expiry_consumed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="authflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("purpose", "sign_in"),
                        ("session_family__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("purpose", "link"),
                        ("session_family__isnull", False),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="auth_flow_purpose_binding_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_name__isnull", False)),
                name="auth_profile_display_name_not_null",
            ),
        ),
    ]
