# Generated by Django 6.0.7 on 2026-08-14.
# ruff: noqa: RUF012

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [("auths", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="externalidentity",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externalidentity",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalidentity",
            name="email_verification_source",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        email_verified=False,
                        email_verified_at__isnull=True,
                        email_verification_source="",
                    )
                    | Q(
                        email_verified=True,
                        provider="google",
                        email_snapshot__gt="",
                        email_verified_at__isnull=False,
                        email_verification_source="google",
                    )
                ),
                name="auth_identity_verified_email_coherent",
            ),
        ),
    ]
