# Generated by Django 6.0.7 on 2026-09-05
# ruff: noqa: RUF012

from django.db import migrations, models

import auths.models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nativeauthorizationtransaction",
            name="completion_mode",
            field=models.CharField(
                choices=[("redirect", "Redirect"), ("manual_code", "Manual code")],
                db_default=models.Value("redirect"),
                default=auths.models.NativeCompletionMode.REDIRECT,
                max_length=16,
            ),
        ),
    ]
