# Generated by Django 6.0.7 on 2026-09-15 08:34
# ruff: noqa: RUF012

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0002_native_completion_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "claimed_email",
                    models.EmailField(
                        blank=True,
                        editable=False,
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("claimed_at__isnull", True),
                                ("claimed_email__isnull", True),
                            ),
                            models.Q(
                                ("claimed_at__isnull", False),
                                ("claimed_email__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="auth_beta_invite_claim_coherent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("consumed_at__isnull", True),
                            ("claimed_at__isnull", False),
                            _connector="OR",
                        ),
                        name="auth_beta_invite_consumed_claimed",
                    ),
                ],
            },
        ),
    ]
