# Generated by Django 6.0.7 on 2026-08-20.
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [("auths", "0002_externalidentity_email_verification")]

    operations = [
        migrations.CreateModel(
            name="NativeAuthorizationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("fake", "Fake"), ("google", "Google")],
                        max_length=32,
                    ),
                ),
                ("callback_uri", models.CharField(max_length=500)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("app_state_sealed", models.TextField(editable=False)),
                ("code_challenge", models.CharField(editable=False, max_length=128)),
                ("nonce_digest", models.CharField(editable=False, max_length=64)),
                ("nonce_sealed", models.TextField(editable=False)),
                ("pkce_verifier_sealed", models.TextField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "claim_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="NativeExchangeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("code_sealed", models.TextField(editable=False)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("code_challenge", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_code",
                        to="auths.nativeauthorizationtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_exchange_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sessionfamily",
            name="client_kind",
            field=models.CharField(
                choices=[("browser", "Browser"), ("native", "Native")],
                default="browser",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="nativeauthorizationtransaction",
            index=models.Index(
                fields=["status", "expires_at"], name="auth_native_tx_state_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nativeauthorizationtransaction",
            index=models.Index(
                fields=["status", "claim_expires_at"],
                name="auth_native_tx_claim_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nativeauthorizationtransaction",
            index=models.Index(
                fields=["status", "terminal_at"], name="auth_native_tx_terminal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nativeexchangecode",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_native_code_exp_cons_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="nativeauthorizationtransaction",
            constraint=models.CheckConstraint(
                condition=(
                    Q(status="pending", terminal_at__isnull=True)
                    | Q(
                        status="claimed",
                        claimed_at__isnull=False,
                        claim_expires_at__isnull=False,
                        terminal_at__isnull=True,
                    )
                    | Q(
                        status__in=("completed", "denied", "failed"),
                        terminal_at__isnull=False,
                    )
                ),
                name="auth_native_tx_status_coherent",
            ),
        ),
    ]
