# Generated by Django 6.0.7 on 2026-08-25 23:03
# ruff: noqa: RUF012

import uuid

import django.utils.timezone
from django.db import migrations, models

import allies.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ally",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("job", models.CharField(max_length=200)),
                ("personality", models.TextField(max_length=4000)),
                ("appearance_catalog_version", models.CharField(max_length=32)),
                ("appearance_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("workspace_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AllyBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("bound", "Bound"),
                            ("incompatible", "Incompatible"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "receipt_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OnboardingAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempt_token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "browser_binding_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                ("name", models.CharField(max_length=80)),
                ("job", models.CharField(max_length=200)),
                ("personality", models.TextField(max_length=4000)),
                ("appearance_catalog_version", models.CharField(max_length=32)),
                ("appearance_key", models.CharField(max_length=128)),
                ("greeting", models.TextField(max_length=4000)),
                ("reply", models.TextField(blank=True, max_length=4000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProvisioningOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_idempotency_key_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "content_fingerprint",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("retryable", "Retryable"),
                            ("failed", "Failed"),
                            ("repair_required", "Repair required"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=allies.models.default_operation_expiry
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("safe_error_code", models.CharField(blank=True, max_length=64)),
                (
                    "receipt_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
