# Generated by Django 6.0.7 on 2026-08-21 19:37
# ruff: noqa: RUF012

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import allies.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ally",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=allies.models.new_ally_public_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("job", models.CharField(max_length=200)),
                ("personality", models.TextField(max_length=4000)),
                ("appearance_catalog_version", models.CharField(max_length=32)),
                ("appearance_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("workspace_id", "public_id"),
            },
        ),
        migrations.CreateModel(
            name="AllyBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cloud_binding_id",
                    models.CharField(
                        default=allies.models.new_binding_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("bound", "Bound"),
                            ("incompatible", "Incompatible"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "receipt_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binding",
                        to="allies.ally",
                    ),
                ),
            ],
            options={
                "ordering": ("cloud_binding_id",),
            },
        ),
        migrations.CreateModel(
            name="OnboardingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "browser_binding_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                ("name", models.CharField(max_length=80)),
                ("job", models.CharField(max_length=200)),
                ("personality", models.TextField(max_length=4000)),
                ("appearance_catalog_version", models.CharField(max_length=32)),
                ("appearance_key", models.CharField(max_length=128)),
                ("greeting", models.TextField(max_length=4000)),
                ("reply", models.TextField(blank=True, max_length=4000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_attempt",
                        to="allies.ally",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvisioningOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=allies.models.new_operation_public_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "api_idempotency_key_digest",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "content_fingerprint",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("retryable", "Retryable"),
                            ("failed", "Failed"),
                            ("repair_required", "Repair required"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=allies.models.default_operation_expiry
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("safe_error_code", models.CharField(blank=True, max_length=64)),
                (
                    "receipt_digest",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_operation",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_operations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "public_id"),
            },
        ),
        migrations.AddIndex(
            model_name="ally",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="ally_workspace_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="allies_binding_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="allies_binding_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("receipt_digest__gt", ""), ("status", "bound")),
                    models.Q(("status", "bound"), _negated=True),
                    _connector="OR",
                ),
                name="allies_binding_bound_receipt_required",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingattempt",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="attempt_expiry_consumed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ally__isnull", True),
                        ("consumed_at__isnull", True),
                        ("reply__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("ally__isnull", False),
                        ("consumed_at__isnull", False),
                        ("reply__gt", ""),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="allies_attempt_consumption_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="provisioningoperation",
            index=models.Index(
                fields=["status", "next_attempt_at", "lease_expires_at"],
                name="allies_operation_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="provisioningoperation",
            index=models.Index(
                fields=["workspace", "user", "created_at"],
                name="allies_operation_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user", "api_idempotency_key_digest"),
                name="allies_operation_identity_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("api_idempotency_key_digest__regex", "^[0-9a-fA-F]{64}$"),
                    ("content_fingerprint__regex", "^[0-9a-fA-F]{64}$"),
                ),
                name="allies_operation_digests_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="allies_operation_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="allies_operation_attempt_count_nonnegative",
            ),
        ),
    ]
