# Generated by Django 6.0.7 on 2026-08-25 23:03
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("allies", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ally",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allies",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="allybinding",
            name="ally",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binding",
                to="allies.ally",
            ),
        ),
        migrations.AddField(
            model_name="onboardingattempt",
            name="ally",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_attempt",
                to="allies.ally",
            ),
        ),
        migrations.AddField(
            model_name="onboardingattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="provisioningoperation",
            name="binding",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provisioning_operation",
                to="allies.allybinding",
            ),
        ),
        migrations.AddField(
            model_name="provisioningoperation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provisioning_operations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="provisioningoperation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provisioning_operations",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="ally",
            index=models.Index(
                fields=["workspace", "created_at"], name="ally_workspace_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="allies_binding_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="allies_binding_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="allybinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("receipt_digest__gt", ""), ("status", "bound")),
                    models.Q(("status", "bound"), _negated=True),
                    _connector="OR",
                ),
                name="allies_binding_bound_receipt_required",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingattempt",
            index=models.Index(
                fields=["expires_at", "consumed_at"], name="attempt_expiry_consumed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ally__isnull", True),
                        ("consumed_at__isnull", True),
                        ("reply__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("ally__isnull", False),
                        ("consumed_at__isnull", False),
                        ("reply__gt", ""),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="allies_attempt_consumption_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="provisioningoperation",
            index=models.Index(
                fields=["status", "next_attempt_at", "lease_expires_at"],
                name="allies_operation_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="provisioningoperation",
            index=models.Index(
                fields=["workspace", "user", "created_at"],
                name="allies_operation_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user", "api_idempotency_key_digest"),
                name="allies_operation_identity_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("api_idempotency_key_digest__regex", "^[0-9a-fA-F]{64}$"),
                    ("content_fingerprint__regex", "^[0-9a-fA-F]{64}$"),
                ),
                name="allies_operation_digests_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="allies_operation_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisioningoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="allies_operation_attempt_count_nonnegative",
            ),
        ),
    ]
