# Generated by Django 6.0.7 on 2026-09-07
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningoperation",
            name="readiness_hint_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
