/**
 * AUTO-GENERATED by html_to_jsx.mjs — visual tree from design HTML.
 * Do not freehand-redraw layout. Wire handlers / drawers on top of this file.
 */
"use client";

import { useLayoutEffect, useRef, useState } from "react";

const ART_W = 375;
const ART_H = 812;

export type AllowNotificationsAlliesExactProps = {
  className?: string;
  onClose?: () => void;
};

export function AllowNotificationsAlliesExact({ className, onClose }: AllowNotificationsAlliesExactProps) {
  void onClose;

  const hostRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(1);

  useLayoutEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const measure = () => {
      const w = el.clientWidth || ART_W;
      setScale(w / ART_W);
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  return (
    <div
      ref={hostRef}
      className={["relative w-full overflow-hidden", className].filter(Boolean).join(" ")}
      style={{
        height: "100dvh",
        minHeight: "100dvh",
        margin: 0,
        padding: 0,
        backgroundColor: "#000",
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          width: ART_W,
          height: ART_H,
          transform: `scale(${scale})`,
          transformOrigin: "top left",
        }}
      >
        <div style={{backgroundColor: '#fff', overflow: 'hidden', width: 375, minWidth: 375, maxWidth: 375, minHeight: 812, maxHeight: 812, position: 'relative', margin: '0px auto'}}>
          <div style={{display: 'flex', flexDirection: 'column', rowGap: 36, alignItems: 'center', justifyContent: 'flex-start', left: 32, top: 'calc(-87px + 50%)', width: 311, position: 'absolute'}}>
            <div style={{borderRadius: 16, backgroundColor: '#f3f3f3', overflow: 'hidden', width: '100%', height: 64, position: 'relative', flexShrink: 0}}>
              <div style={{display: 'flex', flexDirection: 'row', gridColumnGap: 12, alignItems: 'center', justifyContent: 'flex-start', left: 14, top: 12, width: 'min-content', position: 'absolute'}}>
                <div style={{borderRadius: 10, backgroundColor: '#ff2d55', overflow: 'hidden', width: '41.1px', height: 40, position: 'relative', flexShrink: 0}}>
                  <div style={{overflow: 'hidden', left: 'calc(-12.5px + 50%)', top: 'calc(-13.3px + 50%)', width: '24.4px', height: '26.7px', position: 'absolute'}}>
                    <img data-figma-node-id="313:1103" data-figma-asset="fill" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788549808/figma-screens/batch_mtncdh94_qyahc/allow-notifications-allies/assets/fill.svg" alt="fill" width={24} height={27} style={{left: '-3.7%', top: '-3.4%', right: '-3.2%', bottom: '-3%', width: '106.9%', height: '106.4%', position: 'absolute'}} />
                    <div style={{overflow: 'hidden', left: 'calc(-8.9px + 50%)', top: '6.2px', width: '10.2px', height: '7.2px', position: 'absolute'}}>
                      <div style={{overflow: 'hidden', left: 0, top: 0, width: '3.8px', height: '7.2px', position: 'absolute'}}>
                        <svg width="3.836169958114624" height="7.2023606300354" viewBox="0 0 3.836169958114624 7.2023606300354" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '99.9%', height: '100%', position: 'absolute'}}>
                          <path d="M1.9181 0C2.9775 0 3.8362 1.6125 3.8362 3.6012 3.8362 5.5899 2.9775 7.2024 1.9181 7.2024 0.8587 7.2024 0 5.5899 0 3.6012 0 1.6125 0.8587 0 1.9181 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                        </svg>
                        <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '99.9%', height: '99.9%', position: 'absolute'}}>
                          <div style={{overflow: 'hidden', left: '-23.6%', top: '29.1%', right: '52.9%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '0.9px -2.1px'}}>
                            <svg width="3.046168804168701" height="2.7124435901641846" viewBox="0 0 3.046168804168701 2.7124435901641846" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-112.3%', bottom: '11%', width: '112.3%', height: '89%', position: 'absolute'}}>
                              <path d="M1.6415 0.2109l1.2911 2.2992c0.0508 0.0906-0.0146 0.2023-0.1185 0.2023h-2.582c-0.1038 0-0.1693-0.1118-0.1185-0.2023l1.291-2.2992c0.0519-0.0924 0.185-0.0924 0.2369 0z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                            </svg>
                          </div>
                        </div>
                      </div>
                      <div style={{overflow: 'hidden', left: '6.4px', top: 0, width: '3.8px', height: '7.2px', position: 'absolute'}}>
                        <svg width="3.836169958114624" height="7.2023606300354" viewBox="0 0 3.836169958114624 7.2023606300354" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                          <path d="M1.9181 0C2.9775 0 3.8362 1.6125 3.8362 3.6012 3.8362 5.5899 2.9775 7.2024 1.9181 7.2024 0.8587 7.2024 0 5.5899 0 3.6012 0 1.6125 0.8587 0 1.9181 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                        </svg>
                        <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                          <div style={{overflow: 'hidden', left: '-23.6%', top: '29.1%', right: '52.9%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '0.9px -2.1px'}}>
                            <svg width="3.046168804168701" height="2.7124435901641846" viewBox="0 0 3.046168804168701 2.7124435901641846" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-112.3%', bottom: '11%', width: '112.3%', height: '89%', position: 'absolute'}}>
                              <path d="M1.6415 0.2109l1.2911 2.2992c0.0508 0.0906-0.0146 0.2023-0.1185 0.2023h-2.582c-0.1038 0-0.1693-0.1118-0.1185-0.2023l1.291-2.2992c0.0519-0.0924 0.185-0.0924 0.2369 0z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                            </svg>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style={{display: 'flex', flexDirection: 'column', rowGap: 8, alignItems: 'start', justifyContent: 'flex-start', width: 213, position: 'relative', flexShrink: 0}}>
                  <div style={{borderRadius: 4, backgroundColor: '#d9d9d9', overflow: 'hidden', width: 60, height: 18, position: 'relative', flexShrink: 0}}>
                  </div>
                  <div style={{borderRadius: 4, backgroundColor: '#d9d9d9', overflow: 'hidden', width: '100%', height: 14, position: 'relative', flexShrink: 0}}>
                  </div>
                </div>
              </div>
            </div>
            <div style={{display: 'flex', flexDirection: 'column', rowGap: 12, alignItems: 'center', justifyContent: 'flex-start', width: '100%', height: 74, position: 'relative', flexShrink: 0}}>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 20, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.96px', color: '#121212', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Keep up with your allies</span>
              <span className="text" style={{display: 'inline', textAlign: 'center', fontSize: 16, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.49px', color: '#757575', width: 311, position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Allow notifications so you can track tasks, reminders, and reach goals faster</span>
            </div>
          </div>
          <div style={{display: 'flex', flexDirection: 'column', rowGap: 18, alignItems: 'start', justifyContent: 'flex-start', left: 20, top: 640, width: 335, position: 'absolute'}}>
            <div style={{borderRadius: 60, backgroundColor: '#f3f3f3', display: 'flex', flexDirection: 'row', gridColumnGap: 10, alignItems: 'center', justifyContent: 'center', width: '100%', height: 48, position: 'relative', flexShrink: 0, padding: 10}}>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 18, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.66px', color: '#121212', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>I’ll do this later</span>
            </div>
            <div style={{borderRadius: 60, backgroundColor: '#ff2d55', display: 'flex', flexDirection: 'row', gridColumnGap: 10, alignItems: 'center', justifyContent: 'center', width: '100%', height: 48, position: 'relative', flexShrink: 0, padding: 10}}>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 18, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.66px', color: '#fff', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Allow notifications</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AllowNotificationsAlliesExact;
