/**
 * AUTO-GENERATED by html_to_jsx.mjs — visual tree from design HTML.
 * Do not freehand-redraw layout. Wire handlers / drawers on top of this file.
 */
"use client";

import { useLayoutEffect, useRef, useState } from "react";

const ART_W = 375;
const ART_H = 812;

export type AuthAllies1ExactProps = {
  className?: string;
  onClose?: () => void;
};

export function AuthAllies1Exact({ className, onClose }: AuthAllies1ExactProps) {
  void onClose;

  const hostRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(1);

  useLayoutEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const measure = () => {
      const w = el.clientWidth || ART_W;
      setScale(w / ART_W);
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  return (
    <div
      ref={hostRef}
      className={["relative w-full overflow-hidden", className].filter(Boolean).join(" ")}
      style={{
        height: "100dvh",
        minHeight: "100dvh",
        margin: 0,
        padding: 0,
        backgroundColor: "#000",
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          width: ART_W,
          height: ART_H,
          transform: `scale(${scale})`,
          transformOrigin: "top left",
        }}
      >
        <div style={{backgroundColor: '#fff', overflow: 'hidden', width: 375, minWidth: 375, maxWidth: 375, minHeight: 812, maxHeight: 812, position: 'relative', margin: '0px auto'}}>
          <div style={{borderRadius: 16, backgroundColor: '#f3f3f3', overflow: 'hidden', left: 20, top: 649, width: 335, height: 105, position: 'absolute'}}>
            <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 16, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.49px', color: '#121212', left: 14, top: 'calc(-38.5px + 50%)', width: 272, position: 'absolute', lineHeight: '120%'}}>When the text field increases in height, we reduce the corner radius and keep the button aligned at the button, it doesn’t go anywhere, scroll is allowed in the text field</span>
            <div style={{borderRadius: 24, backgroundColor: '#fd304f', overflow: 'hidden', right: 6, bottom: 6, width: 37, height: 36, position: 'absolute'}}>
              <div style={{overflow: 'hidden', left: 9, top: 9, width: 18, height: 18, position: 'absolute'}}>
                <img data-figma-node-id="311:776" data-figma-asset="Group" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788536362/figma-screens/batch_mtn4dagx_xeit5/auth-allies-1/assets/group.svg" alt="Group" width={16} height={16} style={{left: '6.8%', top: '7.1%', right: '7.1%', bottom: '6.8%', width: '86.1%', height: '86.1%', position: 'absolute'}} />
              </div>
            </div>
          </div>
          <div style={{display: 'flex', flexDirection: 'column', rowGap: 18, alignItems: 'start', justifyContent: 'flex-start', left: 20, top: 68, width: 335, position: 'absolute'}}>
            <div style={{display: 'flex', flexDirection: 'row', gridColumnGap: 12, alignItems: 'center', justifyContent: 'center', width: 'min-content', position: 'relative', flexShrink: 0}}>
              <div style={{borderRadius: 16, backgroundColor: '#fd304f', overflow: 'hidden', width: '24.6px', height: 24, position: 'relative', flexShrink: 0}}>
                <img data-figma-node-id="311:782" data-figma-asset="Vector" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788536364/figma-screens/batch_mtn4dagx_xeit5/auth-allies-1/assets/vector.svg" alt="Vector" width={17} height={16} style={{left: '13.6%', top: '13.5%', right: '13.9%', bottom: '13.9%', width: '72.5%', height: '72.7%', position: 'absolute'}} />
                <div style={{overflow: 'hidden', left: '10.4px', top: '7.8px', width: '7.4px', height: '4.2px', position: 'absolute'}}>
                  <div style={{overflow: 'hidden', left: 0, top: 0, width: '2.4px', height: '4.2px', position: 'absolute'}}>
                    <svg width="2.43894362449646" height="4.199999809265137" viewBox="0 0 2.43894362449646 4.199999809265137" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: '0.1%', top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                      <path d="M1.2195 0C1.893 0 2.4389 0.9403 2.4389 2.1 2.4389 3.2597 1.893 4.2 1.2195 4.2 0.5459 4.2 0 3.2597 0 2.1 0 0.9403 0.5459 0 1.2195 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                    </svg>
                    <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                      <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '53%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '0.6px -1.2px'}}>
                        <svg width="1.7763493061065674" height="1.724505662918091" viewBox="0 0 1.7763493061065674 1.724505662918091" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                          <path d="M0.8882 0L1.7763 1.7245H0L0.8882 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                        </svg>
                      </div>
                    </div>
                  </div>
                  <div style={{overflow: 'hidden', left: '4.9px', top: 0, width: '2.4px', height: '4.2px', position: 'absolute'}}>
                    <svg width="2.43894362449646" height="4.199999809265137" viewBox="0 0 2.43894362449646 4.199999809265137" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: '0.1%', top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                      <path d="M1.2195 0C1.893 0 2.4389 0.9403 2.4389 2.1 2.4389 3.2597 1.893 4.2 1.2195 4.2 0.5459 4.2 0 3.2597 0 2.1 0 0.9403 0.5459 0 1.2195 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                    </svg>
                    <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                      <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '53%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '0.6px -1.2px'}}>
                        <svg width="1.7763493061065674" height="1.724505662918091" viewBox="0 0 1.7763493061065674 1.724505662918091" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                          <path d="M0.8882 0L1.7763 1.7245H0L0.8882 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 18, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.92px', color: '#121212', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Sally Morano</span>
            </div>
            <span className="text" style={{display: 'inline', textAlign: 'left', lineHeight: 22, fontSize: 16, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.48px', color: '#121212', width: '100%', position: 'relative', flexShrink: 0}}>Welcome! I am your ally, and I am thrilled to help you make your day easier, more productive, and fun. Think of me as your always-available partner for brainstorming, writing, learning, and organising. <br /><br />No task is too big or too small, and I am constantly learning new ways to assist you better. Let us collaborate and build something great together.<br /><br /><span style={{fontWeight: 600, letterSpacing: '-0.50px', lineHeight: '120%'}}>🌟 What We Can Do Together</span><br /><br />Chat Freely: Ask me questions about history, science, pop culture, or everyday facts.<br /><br />Brainstorm Ideas: Outline your next big business project, travel itinerary, or workout plan.</span>
          </div>
          <div style={{backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.7) 20.7%, rgba(0,0,0,0.7) 67.7%)', backgroundBlendMode: 'normal', left: 0, top: 0, width: 375, height: 812, opacity: '0.4', position: 'absolute'}}>
          </div>
          <div style={{borderRadius: 30, backgroundColor: '#fff', overflow: 'hidden', left: 12, top: 352, width: 351, height: 402, position: 'absolute'}}>
            <span className="text" style={{display: 'inline', textAlign: 'left', lineHeight: 20, fontSize: 16, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.49px', color: '#121212', left: 20, top: 184, width: 311, position: 'absolute'}}>Your ally has been saved but you need to set up an account to use it.</span>
            <div style={{borderRadius: 18, backgroundColor: '#121212', display: 'flex', flexDirection: 'row', gridColumnGap: 12, alignItems: 'center', justifyContent: 'center', top: 24, right: 20, width: 36, height: 36, position: 'absolute', padding: '7.2px'}}>
              <div style={{overflow: 'hidden', width: 24, height: 24, position: 'relative', flexShrink: 0}}>
                <svg width="11.98522937297821" height="11.985238909721375" viewBox="0 0 11.98522937297821 11.985238909721375" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: '24.6%', top: '24.6%', right: '25.5%', bottom: '25.5%', width: '49.9%', height: '49.9%', position: 'absolute'}}>
                  <path d="M0 10.4852L5.2426 5.2426M10.4852 0L5.2426 5.2426M5.2426 5.2426L0 0M5.2426 5.2426L10.4852 10.4852" transform=" translate(0.8572937122698102 0.8572936146818446)" style={{stroke: '#fff', strokeWidth: '1.4999998807907104', strokeLinecap: 'round', strokeLinejoin: 'round'}} />
                </svg>
              </div>
            </div>
            <span className="text" style={{display: 'inline', textAlign: 'center', fontSize: 14, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.47px', color: '#a0a0a0', left: 20, top: 344, width: 311, position: 'absolute', lineHeight: '120%'}}>By continuing, you agree to our <span style={{textDecoration: 'underline', letterSpacing: '-0.47px', lineHeight: '120%'}}>Terms of Service</span> and have read our <span style={{textDecoration: 'underline', letterSpacing: '-0.46px', lineHeight: '120%'}}>Privacy Policy</span></span>
            <div style={{borderRadius: 100, backgroundColor: '#f3f3f3', overflow: 'hidden', left: 20, top: 260, width: 311, height: 48, position: 'absolute'}}>
              <div style={{display: 'flex', flexDirection: 'row', gridColumnGap: 12, alignItems: 'center', justifyContent: 'flex-start', left: 'calc(-98.9px + 50%)', top: 'calc(-12px + 50%)', width: 'min-content', position: 'absolute'}}>
                <div style={{overflow: 'hidden', width: '23.5px', height: 24, position: 'relative', flexShrink: 0}}>
                  <div style={{overflow: 'hidden', left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                    <img data-figma-node-id="311:839" data-figma-asset="xmark (7) 1" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788536368/figma-screens/batch_mtn4dagx_xeit5/auth-allies-1/assets/xmark-7-1.svg" alt="xmark (7) 1" width={24} height={24} style={{left: '-0.7%', top: '-0.4%', right: '-0.7%', bottom: '-0.7%', width: '101.5%', height: '101.2%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '0.2px 0.1px'}} />
                  </div>
                </div>
                <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 18, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.66px', color: '#121212', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Sign up with Google</span>
              </div>
            </div>
            <div style={{display: 'flex', flexDirection: 'column', rowGap: 12, alignItems: 'start', justifyContent: 'flex-start', left: 20, top: 36, width: 252, position: 'absolute'}}>
              <div style={{borderRadius: 40, backgroundColor: '#fd304f', overflow: 'hidden', width: '61.6px', height: 60, position: 'relative', flexShrink: 0}}>
                <img data-figma-node-id="311:821" data-figma-asset="Vector" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788536370/figma-screens/batch_mtn4dagx_xeit5/auth-allies-1/assets/vector-2.svg" alt="Vector" width={42} height={41} style={{left: '13.6%', top: '13.5%', right: '13.9%', bottom: '13.9%', width: '72.5%', height: '72.7%', position: 'absolute'}} />
                <div style={{overflow: 'hidden', left: '26.1px', top: '19.6px', width: '18.4px', height: '10.5px', position: 'absolute'}}>
                  <div style={{overflow: 'hidden', left: 0, top: 0, width: '6.1px', height: '10.5px', position: 'absolute'}}>
                    <svg width="6.0973591804504395" height="10.5" viewBox="0 0 6.0973591804504395 10.5" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                      <path d="M3.0487 0C4.7325 0 6.0974 2.3508 6.0974 5.25 6.0974 8.1492 4.7325 10.5 3.0487 10.5 1.3648 10.5 0 8.1492 0 5.25 0 2.3508 1.3648 0 3.0487 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                    </svg>
                    <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                      <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '53%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '1.4px -3.1px'}}>
                        <svg width="4.440873146057129" height="4.3112640380859375" viewBox="0 0 4.440873146057129 4.3112640380859375" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                          <path d="M2.2204 0L4.4409 4.3113H0L2.2204 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                        </svg>
                      </div>
                    </div>
                  </div>
                  <div style={{overflow: 'hidden', left: '12.3px', top: 0, width: '6.1px', height: '10.5px', position: 'absolute'}}>
                    <svg width="6.0973591804504395" height="10.5" viewBox="0 0 6.0973591804504395 10.5" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                      <path d="M3.0487 0C4.7325 0 6.0974 2.3508 6.0974 5.25 6.0974 8.1492 4.7325 10.5 3.0487 10.5 1.3648 10.5 0 8.1492 0 5.25 0 2.3508 1.3648 0 3.0487 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                    </svg>
                    <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                      <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '53%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '1.4px -3.1px'}}>
                        <svg width="4.440873146057129" height="4.3112640380859375" viewBox="0 0 4.440873146057129 4.3112640380859375" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                          <path d="M2.2204 0L4.4409 4.3113H0L2.2204 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 24, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.88px', color: '#121212', width: '100%', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Create your<br />account</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AuthAllies1Exact;
