# Generated by Django 6.0.7 on 2026-09-09 04:01
# ruff: noqa: RUF012

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0001_initial"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="routine",
            name="routine_deleted_state_coherent_chk",
        ),
        migrations.AddConstraint(
            model_name="routine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deleted_at__isnull", False), ("state", "deleted")),
                    models.Q(
                        models.Q(("state", "deleted"), _negated=True),
                        ("deleted_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="routine_deleted_state_coherent_chk",
            ),
        ),
    ]
