# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0002_deleted_state_coherence"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineDeletionConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_digest",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("main_conversation_id", models.UUIDField()),
                ("expected_revision", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unconsumed", "Unconsumed"),
                            ("consumed", "Consumed"),
                        ],
                        default="unconsumed",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_deletion_confirmations",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_deletion_confirmations",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_deletion_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_confirmations",
                        to="routines.routine",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_deletion_confirmations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["routine", "state"],
                        name="routine_delete_confirm_idx",
                    ),
                    models.Index(
                        fields=["workspace", "owner", "state"],
                        name="routine_confirm_scope_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("consumed_at__isnull", False),
                                ("state", "consumed"),
                            ),
                            models.Q(
                                models.Q(("state", "consumed"), _negated=True),
                                ("consumed_at__isnull", True),
                                _connector="AND",
                            ),
                            _connector="OR",
                        ),
                        name="routine_confirm_state_coherent_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expected_revision__gt", 0)),
                        name="routine_confirm_revision_positive_chk",
                    ),
                ],
            },
        ),
    ]
