# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0003_routinedeletionconfirmation"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineManagementReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(max_length=16)),
                (
                    "outcome",
                    models.CharField(default="saved", max_length=16),
                ),
                ("result_code", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField()),
                ("schedule_state", models.CharField(max_length=16)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_management_receipts",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_management_receipts",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "confirmation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="management_receipt",
                        to="routines.routinedeletionconfirmation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_management_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="management_receipts",
                        to="routines.routine",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_management_receipts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["routine", "created_at"],
                        name="routine_receipt_history_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="routine_receipt_revision_positive_chk",
                    ),
                ],
            },
        ),
    ]
