# Generated by Django 6.0.7 on 2026-09-09 05:58
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0004_routinemanagementreceipt"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("observed_revision", models.PositiveIntegerField()),
                ("observed_schedule_generation", models.PositiveIntegerField()),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("admitted", "Admitted"),
                            ("replay", "Replay"),
                            ("skipped_active", "Skipped active"),
                            ("delayed", "Delayed"),
                            ("recovered", "Recovered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("delayed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_occurrences",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_occurrences",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_occurrences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="routines.routine",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_occurrences",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RoutineRunSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("routine_revision", models.PositiveIntegerField()),
                ("schedule_generation", models.PositiveIntegerField()),
                ("title_snapshot", models.CharField(max_length=120)),
                ("execution_prompt", models.TextField(max_length=16384)),
                ("schedule_snapshot", models.JSONField()),
                ("timezone", models.CharField(max_length=64)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "occurrence_disposition",
                    models.CharField(
                        choices=[
                            ("admitted", "Admitted"),
                            ("replay", "Replay"),
                            ("skipped_active", "Skipped active"),
                            ("delayed", "Delayed"),
                            ("recovered", "Recovered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("delayed", models.BooleanField(default=False)),
                ("main_conversation_id", models.UUIDField()),
                ("run_conversation_id", models.UUIDField(unique=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("working", "Working"),
                            ("approval_waiting", "Approval waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_run_snapshots",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_run_snapshots",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_snapshot",
                        to="routines.routineoccurrence",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_run_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_snapshots",
                        to="routines.routine",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_run_snapshots",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RoutineDispatchOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command_id", models.UUIDField(unique=True)),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("command_bytes", models.BinaryField(default=bytes)),
                (
                    "command_byte_length",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "command_sha256",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "command_fingerprint",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=90
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("accepted", "Accepted"),
                            ("reconciliation_needed", "Reconciliation needed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "receipt_digest",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_outboxes",
                        to="routines.routine",
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_outbox",
                        to="routines.routineoccurrence",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_outbox",
                        to="routines.routinerunsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="routineoccurrence",
            index=models.Index(
                fields=["routine", "scheduled_at"], name="routine_occurrence_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routineoccurrence",
            index=models.Index(
                fields=["workspace", "owner", "created_at"],
                name="routine_occurrence_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineoccurrence",
            constraint=models.UniqueConstraint(
                fields=("routine", "scheduled_at"),
                name="routine_occurrence_schedule_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("observed_revision__gt", 0)),
                name="routine_occ_revision_positive_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("observed_schedule_generation__gt", 0)),
                name="routine_occ_generation_positive_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="routinerunsnapshot",
            index=models.Index(
                fields=["routine", "outcome", "created_at"],
                name="routine_run_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routinerunsnapshot",
            index=models.Index(
                fields=["workspace", "owner", "created_at"],
                name="routine_run_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinerunsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("outcome__in", ("queued", "working", "approval_waiting"))
                ),
                fields=("routine",),
                name="routine_active_run_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinerunsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("routine_revision__gt", 0)),
                name="routine_run_revision_positive_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinerunsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("schedule_generation__gt", 0)),
                name="routine_run_generation_positive_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinerunsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("run_conversation_id", models.F("main_conversation_id")),
                    _negated=True,
                ),
                name="routine_run_conversation_distinct_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="routinedispatchoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at", "lease_expires_at"],
                name="routine_dispatch_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("command_byte_length__gte", 0)),
                name="routine_dispatch_length_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("command_sha256", ""),
                    ("command_sha256__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="routine_dispatch_command_sha_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("command_fingerprint", ""),
                    (
                        "command_fingerprint__regex",
                        "^canonical-json-sha256:v1:[0-9a-fA-F]{64}$",
                    ),
                    _connector="OR",
                ),
                name="routine_dispatch_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest", ""),
                    ("receipt_digest__regex", "^[0-9a-fA-F]{64}$"),
                    _connector="OR",
                ),
                name="routine_dispatch_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinedispatchoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_count__gte", 0), ("attempt_count__lte", 5)
                ),
                name="routine_dispatch_attempt_bounded",
            ),
        ),
    ]
