# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_revision9_receipt_fields(apps, schema_editor):
    receipt_model = apps.get_model("routines", "RoutineManagementReceipt")
    routine_model = apps.get_model("routines", "Routine")
    for receipt in receipt_model.objects.all().iterator():
        receipt_model.objects.filter(pk=receipt.pk).update(
            command_id=receipt.command_id or uuid.uuid4(),
            idempotency_key=receipt.idempotency_key or uuid.uuid4(),
            schedule_generation=routine_model.objects.get(
                pk=receipt.routine_id
            ).schedule_generation,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0006_routinedispatchoutbox_attempt_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routinemanagementreceipt",
            name="confirmation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="management_receipt",
                to="routines.routinedeletionconfirmation",
            ),
        ),
        migrations.AddField(
            model_name="routinemanagementreceipt",
            name="command_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="routinemanagementreceipt",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="routinemanagementreceipt",
            name="resume_effective_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routinemanagementreceipt",
            name="schedule_generation",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            backfill_revision9_receipt_fields,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="routinemanagementreceipt",
            name="command_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="routinemanagementreceipt",
            name="idempotency_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="routinemanagementreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("schedule_generation__gt", 0)),
                name="routine_receipt_generation_positive_chk",
            ),
        ),
    ]
