# Generated by Django 6.0.7 on 2026-09-09 09:07
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("routines", "0007_routinereceipt_revision9_fields"),
        ("workspaces", "0002_workspace_runtime_intent_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineApprovalProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_request_id",
                    models.UUIDField(editable=False, unique=True),
                ),
                (
                    "action_attempt_id",
                    models.UUIDField(editable=False, unique=True),
                ),
                ("execution_id", models.UUIDField(editable=False)),
                ("attempt_id", models.UUIDField(editable=False)),
                ("generation", models.PositiveIntegerField(editable=False)),
                ("event_id", models.UUIDField(editable=False, unique=True)),
                ("event_sequence", models.PositiveIntegerField(editable=False)),
                (
                    "event_fingerprint",
                    models.CharField(editable=False, max_length=90),
                ),
                ("action_digest", models.CharField(editable=False, max_length=64)),
                (
                    "provider_idempotency_key",
                    models.CharField(editable=False, max_length=255),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("expires_at", models.DateTimeField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("decision_recorded", "Decision recorded"),
                            ("authorizing", "Authorizing"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("decision", models.CharField(blank=True, default="", max_length=6)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_command_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "decision_idempotency_key",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "decision_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=90,
                    ),
                ),
                ("permission_consumed", models.BooleanField(blank=True, null=True)),
                (
                    "action_attempt_state",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "last_result_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "local_expired_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_projection_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_projections",
                        to="allies.ally",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_projections",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "deciding_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_projections",
                        to="routines.routineoccurrence",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_projections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_projections",
                        to="routines.routine",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_projections",
                        to="routines.routinerunsnapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_projections",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="RoutineApprovalCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("routine.approval_decision", "Approval decision"),
                            ("routine.cancel_wait", "Cancel wait"),
                        ],
                        max_length=32,
                    ),
                ),
                ("command_id", models.UUIDField(editable=False, unique=True)),
                (
                    "idempotency_key",
                    models.UUIDField(editable=False, unique=True),
                ),
                ("command_bytes", models.BinaryField(default=bytes)),
                (
                    "command_byte_length",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "command_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "command_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=90,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("accepted", "Accepted"),
                            ("reconciliation_needed", "Reconciliation needed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                    ),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("receipt_bytes", models.BinaryField(default=bytes)),
                (
                    "receipt_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replacing_occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_approval_cancel_commands",
                        to="routines.routineoccurrence",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commands",
                        to="routines.routineapprovalprojection",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="routineapprovalprojection",
            index=models.Index(
                fields=["workspace", "owner", "status", "created_at"],
                name="routine_appr_scope_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routineapprovalprojection",
            index=models.Index(
                fields=["status", "expires_at", "id"],
                name="routine_appr_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.UniqueConstraint(
                fields=("attempt_id", "event_sequence"),
                name="routine_appr_attempt_seq_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(event_sequence__gt=0),
                name="routine_appr_event_sequence_positive_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(generation__gte=0),
                name="routine_appr_generation_nonnegative_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(action_digest__regex=r"^[0-9a-f]{64}$"),
                name="routine_appr_action_digest_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    event_fingerprint__regex=r"^canonical-json-sha256:v1:[0-9a-f]{64}$"
                ),
                name="routine_appr_event_fingerprint_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(decision="")
                | models.Q(decision__in=("approve", "reject")),
                name="routine_appr_decision_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(expires_at__gt=models.F("created_at")),
                name="routine_appr_expiry_after_created_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="routineapprovalcommand",
            index=models.Index(
                fields=["status", "next_attempt_at", "lease_expires_at"],
                name="routine_appr_cmd_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.UniqueConstraint(
                fields=("approval", "kind"),
                name="routine_appr_command_kind_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(command_byte_length__gte=0),
                name="routine_appr_cmd_length_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(command_sha256__regex=r"^[0-9a-f]{64}$"),
                name="routine_appr_cmd_sha_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    command_fingerprint__regex=r"^canonical-json-sha256:v1:[0-9a-f]{64}$"
                ),
                name="routine_appr_cmd_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(receipt_digest="")
                | models.Q(receipt_digest__regex=r"^[0-9a-f]{64}$"),
                name="routine_appr_receipt_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineapprovalcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(attempt_count__gte=0)
                & models.Q(attempt_count__lte=5),
                name="routine_appr_cmd_attempt_bounded",
            ),
        ),
    ]
