# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_message_routine_action"),
        ("routines", "0009_routinetoolcall"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="created_routines",
                to="chat.message",
            ),
        ),
    ]
