# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("chat", "0006_message_queue_claims"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=16,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=127)),
                ("expected_size", models.PositiveBigIntegerField()),
                ("actual_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "object_key",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=500
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("receiving", "Receiving"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("retained", "Retained"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cleanup_pending", "Cleanup pending"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=1)),
                ("write_fence", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("cleanup_after", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_versions",
                        to="allies.ally",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_file_versions",
                        to="chat.message",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_versions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilePublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_digest", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("retry_pending", "Retry pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploading",
                        max_length=24,
                    ),
                ),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("retry_due_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("retry_attempts", models.PositiveSmallIntegerField(default=0)),
                ("result_revision", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "result_lease_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "result_outcome",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_publications",
                        to="allies.allybinding",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_publications",
                        to="chat.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_links",
                        to="files.fileversion",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_links",
                        to="chat.message",
                    ),
                ),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["workspace", "ally", "state"],
                name="files_version_scope_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["state", "cleanup_after"], name="files_version_cleanup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fileversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_size__gt", 0), ("expected_size__lte", 25000000)
                ),
                name="files_version_expected_size_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_size__isnull", True),
                    models.Q(("actual_size__gt", 0), ("actual_size__lte", 25000000)),
                    _connector="OR",
                ),
                name="files_version_actual_size_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                name="files_version_sha256_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gt", 0)),
                name="files_version_generation_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="filepublication",
            index=models.Index(
                fields=["state", "retry_due_at", "lease_until"],
                name="files_publication_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_digest__regex", "^[0-9a-f]{64}$")),
                name="files_publication_request_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gt", 0)),
                name="files_publication_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("retry_attempts__lte", 5)),
                name="files_publication_retry_attempts_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagefile",
            constraint=models.UniqueConstraint(
                fields=("message", "position"), name="files_message_position_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagefile",
            constraint=models.UniqueConstraint(
                fields=("message", "file"), name="files_message_file_uniq"
            ),
        ),
    ]
