# Generated by Django 6.0.7 on 2026-09-09
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("files", "0001_file_domain_foundation")]

    operations = [
        migrations.CreateModel(
            name="FileStorageAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("retained_bytes", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_storage_account",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileStagingObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500, unique=True)),
                ("generation", models.PositiveIntegerField()),
                ("write_fence", models.UUIDField(editable=False)),
                ("cleanup_after", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_objects",
                        to="files.fileversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="filestagingobject",
            index=models.Index(
                fields=["cleanup_after", "id"], name="files_staging_cleanup_idx"
            ),
        ),
    ]
