# Generated by Django 6.0.7 on 2026-09-09 23:03
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("chat", "0007_message_file_preparation"),
        ("files", "0002_file_admission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDraftRecovery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=16000)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_drafts",
                        to="allies.ally",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_draft_recovery",
                        to="chat.message",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileDraftFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_links",
                        to="files.fileversion",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_links",
                        to="files.filedraftrecovery",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="filedraftrecovery",
            index=models.Index(
                fields=["owner", "ally", "discarded_at"], name="files_draft_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filedraftfile",
            constraint=models.UniqueConstraint(
                fields=("draft", "file"), name="files_draft_file_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="filedraftfile",
            constraint=models.UniqueConstraint(
                fields=("draft", "position"), name="files_draft_position_uniq"
            ),
        ),
    ]
