# Generated by Django 6.0.7 on 2026-09-09 23:40
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allies", "0003_provisioningoperation_readiness_hint_received_at"),
        ("chat", "0008_dispatch_file_manifest"),
        ("files", "0003_file_preparation_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAllyTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tombstoned_at", models.DateTimeField()),
                (
                    "foundry_cleanup_receipt",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="filepublication",
            name="files_publication_request_digest_valid",
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="cleanup_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="cleanup_last_error",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="cleanup_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="kind",
            field=models.CharField(
                choices=[
                    ("staging", "Staging"),
                    ("promotion", "Promotion"),
                    ("object", "Object"),
                ],
                default="staging",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="inspection_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="inspection_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="inspection_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="files",
                to="files.filepublication",
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="reserved_accounted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="retained_accounted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="source_version_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="filepublication",
            name="request_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="filestagingobject",
            index=models.Index(
                fields=["deleted_at", "cleanup_after", "id"],
                name="files_object_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepublication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("request_digest", ""),
                    ("request_digest__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="files_publication_request_digest_valid",
            ),
        ),
        migrations.AddField(
            model_name="fileallytombstone",
            name="ally",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_tombstone",
                to="allies.ally",
            ),
        ),
    ]
