# Generated by Django 6.0.7 on 2026-09-10 22:50
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_fileversion_inspection_lease_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestagingobject",
            name="io_outcome",
            field=models.CharField(
                choices=[
                    ("none", "Not started"),
                    ("in_flight", "In flight"),
                    ("completed", "Completed"),
                    ("ambiguous", "Ambiguous"),
                    ("aborted", "Aborted"),
                ],
                default="none",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="version_key_marker",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=500
            ),
        ),
        migrations.AddField(
            model_name="filestagingobject",
            name="version_id_marker",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=128
            ),
        ),
    ]
