import { readFile, readdir, writeFile } from 'node:fs/promises';
import { normalizePathMotion } from './svg-path-motion.mjs';

const root = new URL('../', import.meta.url);
const artwork = {};
if ((await readdir(new URL('artwork/', root))).filter(name => name.endsWith('.svg')).length !== 20) throw Error('Expected exactly twenty approved SVGs');
for (const shape of ['boxy', 'ghosty', 'rocky', 'rolly']) {
  artwork[shape] = {};
  for (const state of ['idle', 'thinking', 'sleeping', 'waking', 'falling-asleep']) {
    const svg = (await readFile(new URL(`artwork/${state}_${shape}.svg`, root), 'utf8')).replace(/\r\n/g, '\n');
    if (!svg.includes('viewBox="0 0 470 470"') || /<script|<foreignObject|\bon\w+\s*=|(?:href|src)\s*=\s*["'](?!#)/i.test(svg)) throw Error(`Unsafe or invalid artwork: ${state}_${shape}`);
    artwork[shape][state] = normalizePathMotion(svg, state);
  }
}
const runtime = (await readFile(new URL('src/player.js', root), 'utf8')).replace(/\r\n/g, '\n');
await writeFile(new URL('src/generated.ts', root), `// Generated by scripts/generate.mjs from approved artwork and player.js.\nexport const ARTWORK = ${JSON.stringify(artwork)};\nexport const PLAYER_SCRIPT = ${JSON.stringify(runtime)};\n`);
