# Generated by Django 6.0.7 on 2026-08-14 15:21
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from common.identifiers import new_public_id


def new_draft_public_id() -> str:
    return new_public_id("wld")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=new_draft_public_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "capability_digest",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("configuring", "Configuring"),
                            ("ready_for_greeting", "Ready for greeting"),
                            ("greeting_ready", "Greeting ready"),
                            ("reply_pending", "Reply pending"),
                            ("pending_claim", "Pending claim"),
                            ("claimed", "Claimed"),
                            ("expired", "Expired"),
                        ],
                        default="configuring",
                        max_length=24,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("name", models.CharField(blank=True, max_length=80)),
                (
                    "appearance_catalog_version",
                    models.CharField(blank=True, max_length=32),
                ),
                ("appearance_key", models.CharField(blank=True, max_length=128)),
                ("job", models.TextField(blank=True)),
                ("personality", models.TextField(blank=True)),
                (
                    "generation_input_digest",
                    models.CharField(blank=True, max_length=64),
                ),
                ("greeting_text", models.TextField(blank=True)),
                (
                    "greeting_policy_version",
                    models.CharField(blank=True, max_length=32),
                ),
                ("greeting_generated_at", models.DateTimeField(blank=True, null=True)),
                ("reply_text", models.TextField(blank=True)),
                ("reply_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("email_normalized", models.EmailField(blank=True, max_length=254)),
                ("consent_version", models.CharField(blank=True, max_length=64)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claimed_waitlist_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitlistOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("configure", "Configure"),
                            ("generate", "Generate"),
                            ("reply", "Reply"),
                            ("join", "Join"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_digest", models.CharField(editable=False, max_length=64)),
                ("request_digest", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_revision",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("result_lifecycle", models.CharField(blank=True, max_length=24)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="waitlist.waitlistdraft",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="waitlistdraft",
            index=models.Index(
                fields=["lifecycle", "expires_at", "id"],
                name="waitlist_draft_retention_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gt", 0)),
                name="waitlist_draft_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("consent_version", ""),
                        ("email_normalized", ""),
                        ("joined_at__isnull", True),
                    ),
                    models.Q(
                        ("consent_version__gt", ""),
                        ("email_normalized__gt", ""),
                        ("joined_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="waitlist_draft_join_fields_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("capability_digest__isnull", True),
                        ("claimed_at__isnull", False),
                        ("claimed_by__isnull", False),
                        ("expires_at__isnull", True),
                        ("lifecycle", "claimed"),
                    ),
                    models.Q(("lifecycle", "claimed"), _negated=True),
                    _connector="OR",
                ),
                name="waitlist_draft_claim_fields_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("greeting_generated_at__isnull", True), ("greeting_text", "")
                    ),
                    models.Q(
                        ("greeting_generated_at__isnull", False),
                        ("greeting_text__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="waitlist_draft_greeting_fields_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reply_recorded_at__isnull", True), ("reply_text", "")),
                    models.Q(
                        ("reply_recorded_at__isnull", False), ("reply_text__gt", "")
                    ),
                    _connector="OR",
                ),
                name="waitlist_draft_reply_fields_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistoperation",
            index=models.Index(
                fields=["draft", "kind", "status"], name="waitlist_operation_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistoperation",
            constraint=models.UniqueConstraint(
                fields=("draft", "kind", "idempotency_digest"),
                name="waitlist_operation_retry_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlistoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failure_code", ""),
                        ("lease_expires_at__isnull", False),
                        ("result_lifecycle", ""),
                        ("result_revision__isnull", True),
                        ("status", "in_progress"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_code", ""),
                        ("lease_expires_at__isnull", True),
                        ("result_lifecycle__gt", ""),
                        ("result_revision__isnull", False),
                        ("status", "succeeded"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_code__gt", ""),
                        ("lease_expires_at__isnull", True),
                        ("result_lifecycle", ""),
                        ("result_revision__isnull", True),
                        ("status", "failed"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("lease_expires_at__isnull", True),
                        ("result_lifecycle", ""),
                        ("result_revision__isnull", True),
                        ("status", "outcome_unknown"),
                    ),
                    _connector="OR",
                ),
                name="waitlist_operation_state_coherent",
            ),
        ),
    ]
