/**
 * AUTO-GENERATED by html_to_jsx.mjs — visual tree from design HTML.
 * Do not freehand-redraw layout. Wire handlers / drawers on top of this file.
 */
"use client";

import { useLayoutEffect, useRef, useState } from "react";

const ART_W = 375;
const ART_H = 812;

export type WelcomeAllies1ExactProps = {
  className?: string;
  onClose?: () => void;
};

export function WelcomeAllies1Exact({ className, onClose }: WelcomeAllies1ExactProps) {
  void onClose;

  const hostRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(1);

  useLayoutEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const measure = () => {
      const w = el.clientWidth || ART_W;
      setScale(w / ART_W);
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  return (
    <div
      ref={hostRef}
      className={["relative w-full overflow-hidden", className].filter(Boolean).join(" ")}
      style={{
        height: "100dvh",
        minHeight: "100dvh",
        margin: 0,
        padding: 0,
        backgroundColor: "#000",
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          width: ART_W,
          height: ART_H,
          transform: `scale(${scale})`,
          transformOrigin: "top left",
        }}
      >
        <div style={{backgroundColor: '#fff', overflow: 'hidden', width: 375, minWidth: 375, maxWidth: 375, minHeight: 812, maxHeight: 812, position: 'relative', margin: '0px auto'}}>
          <div style={{display: 'flex', flexDirection: 'column', rowGap: 18, alignItems: 'center', justifyContent: 'flex-start', left: 33, top: 337, width: 309, position: 'absolute'}}>
            <div style={{borderRadius: 40, backgroundColor: '#fd304f', overflow: 'hidden', width: '61.6px', height: 60, position: 'relative', flexShrink: 0}}>
              <img data-figma-node-id="312:1027" data-figma-asset="Vector" src="https://res.cloudinary.com/dsxwnm3ib/image/upload/v1788536374/figma-screens/batch_mtn4dagx_xeit5/welcome-allies-1/assets/vector.svg" alt="Vector" width={42} height={41} style={{left: '13.6%', top: '13.5%', right: '13.9%', bottom: '13.9%', width: '72.5%', height: '72.7%', position: 'absolute'}} />
              <div style={{overflow: 'hidden', left: '26.1px', top: '19.6px', width: '18.4px', height: '10.5px', position: 'absolute'}}>
                <div style={{overflow: 'hidden', left: 0, top: 0, width: '6.1px', height: '10.5px', position: 'absolute'}}>
                  <svg width="6.0973591804504395" height="10.5" viewBox="0 0 6.0973591804504395 10.5" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                    <path d="M3.0487 0C4.7325 0 6.0974 2.3508 6.0974 5.25 6.0974 8.1492 4.7325 10.5 3.0487 10.5 1.3648 10.5 0 8.1492 0 5.25 0 2.3508 1.3648 0 3.0487 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                  </svg>
                  <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                    <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '53%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '1.4px -3.1px'}}>
                      <svg width="4.440873146057129" height="4.3112640380859375" viewBox="0 0 4.440873146057129 4.3112640380859375" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                        <path d="M2.2204 0L4.4409 4.3113H0L2.2204 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                      </svg>
                    </div>
                  </div>
                </div>
                <div style={{overflow: 'hidden', left: '12.3px', top: 0, width: '6.1px', height: '10.5px', position: 'absolute'}}>
                  <svg width="6.0973591804504395" height="10.5" viewBox="0 0 6.0973591804504395 10.5" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{left: 0, top: 0, right: 0, bottom: 0, width: '100%', height: '100%', position: 'absolute'}}>
                    <path d="M3.0487 0C4.7325 0 6.0974 2.3508 6.0974 5.25 6.0974 8.1492 4.7325 10.5 3.0487 10.5 1.3648 10.5 0 8.1492 0 5.25 0 2.3508 1.3648 0 3.0487 0Z" style={{fillRule: 'nonzero', fill: '#000'}} />
                  </svg>
                  <div style={{overflow: 'hidden', left: 0, top: '0.1%', right: 0, bottom: '0.1%', width: '100%', height: '99.9%', position: 'absolute'}}>
                    <div style={{overflow: 'hidden', left: '-23.7%', top: '29.1%', right: '52.9%', bottom: '28.5%', width: '70.7%', height: '42.3%', position: 'absolute', maskImage: 'url("data:image/svg+xml', maskRepeat: 'no-repeat', maskType: 'luminance', maskPosition: '1.4px -3.1px'}}>
                      <svg width="4.440873146057129" height="4.3112640380859375" viewBox="0 0 4.440873146057129 4.3112640380859375" fill="none" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" style={{transformOrigin: '0 0', transform: 'rotate(90deg)', left: '100%', top: 0, right: '-103%', bottom: '2.9%', width: '103%', height: '97.1%', position: 'absolute'}}>
                        <path d="M2.2204 0L4.4409 4.3113H0L2.2204 0Z" style={{fillRule: 'nonzero', fill: '#fff'}} />
                      </svg>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div style={{display: 'flex', flexDirection: 'column', rowGap: 12, alignItems: 'center', justifyContent: 'flex-start', width: '100%', position: 'relative', flexShrink: 0}}>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 24, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 600, fontStretch: '100%', letterSpacing: '-0.95px', color: '#121212', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>Looking good, Tolani</span>
              <span className="text" style={{display: 'inline', textAlign: 'left', fontSize: 16, fontFamily: '"Open Runde", Inter, system-ui, sans-serif', fontWeight: 500, fontStretch: '100%', letterSpacing: '-0.49px', color: '#757575', width: 'max-content', position: 'relative', flexShrink: 0, lineHeight: '120%'}}>We’re done with the basics, one more thing</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default WelcomeAllies1Exact;
