# Generated by Django 6.0.7 on 2026-09-10
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("files", "0004_publication_opening_cleanup")]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="inspection_lease_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        )
    ]
